#+LATEX_HEADER: \usepackage{ctex, mathtools, amsthm, booktabs, physics, geometry, hyperref, bm, extarrows}
#+LATEX_HEADER: \hypersetup{colorlinks=true}
#+LATEX_HEADER: \geometry{left=2.5cm, right=2.5cm, top=2cm, bottom=2cm}
#+LATEX_HEADER: \renewcommand\arraystretch{1.5}
#+LATEX_HEADER: \theoremstyle{definition} \newtheorem{definition}{定义}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{theorem}{定理}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{deduction}{推论}[section]
#+LATEX_HEADER: \theoremstyle{remark} \newtheorem{remark}{注释}[section]
#+LATEX_HEADER: \DeclareMathOperator{\diag}{diag}
#+STARTUP: align, latexpreview
#+OPTIONS: toc:nil

* 行列式
** 行列式的概念和基本性质
*** 排列(Permutation)及其逆序数
\[ P_n^m = n(n-1)(n-2)\cdots(n-m+1) = \frac{n!}{(n-m)!} \]

\[ t = \sum_{i=1}^n t_i \]

*** 对换
\begin{theorem}
一个排列中的任意两个元素对换, 排列改变奇偶性.
\end{theorem}

\begin{deduction}
奇排列对换成标准排列的对换次数为奇数, 偶排列对换成标准排列的对换次数为偶数.
\end{deduction}

*** $n$ 阶行列式(Determinant)
\[ 
D_n = \mdet {
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots &        & \vdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn} \\
}
= \sum_{j_1 j_2 \cdots j_n} (-1)^{\tau(j_1 j_2 \cdots j_n)} a_{1j_1} a_{2j_2} \cdots a_{nj_n}
= \det(a_{ij})
\]

*** 行列式的性质
1. $D=D^{\mathrm{T}}$
2. 对换行列式的两行(列), 行列式变号.
   1. 如果行列式有两行(列)完全相同, 则此行列式等于零.
3. 行列式的某一行(列)中所有的元素都乘同一数 $k$, 等于用数 $k$ 乘此行列式.
   1. 行列式中某一行(列)的所有元素的公因子可以提到行列式记号的外面.
   2. 行列式中如果有两行(列)元素成比例, 则此行列式等于零.
4. 行列式具有分行(列)的可加性.
5. 行列式的某一行(列)中所有元素的 $k$ 倍加到另一行(列)对应的元素上去, 行列式不变.

** 行列式按行(列)展开定理
- 余子式 :: 在 $n$ 阶行列式中, 把 $(i,j)$ 元 $a_{ij}$ 所在的第 $i$ 行和第 $j$ 列划去后, 留下来的 $n-1$ 阶行列式叫做 $(i,j)$ 元 $a_{ij}$ 的余子式, 记作 $M_{ij}$.
- 代数余子式 :: $A_{ij} = (-1)^{i+j} M_{ij}$

\begin{equation*}
\sum_{k=1}^n a_{ki}A_{kj} = 
\begin{cases}
D & i=j. \\
0 & i \neq j.
\end{cases}
\end{equation*}
或
\begin{equation*}
\sum_{k=1}^n a_{ik}A_{jk} = 
\begin{cases}
D & i=j. \\
0 & i \neq j.
\end{cases}
\end{equation*}

* 矩阵
** 矩阵的概念
线性变换和矩阵之间存在着一一对应的关系.
- 对角(Diagonal)矩阵 :: $\bm{\varLambda} = \diag(\lambda_1,\lambda_2,\dots,\lambda_n)$
- 单位矩阵 :: $\bm{E} = \diag(1,1,\dots,1)$

** 矩阵的线性运算
满足交换、结合、分配律.

** 矩阵的乘法
\begin{definition}
设 $\bm{A}=(a_{ij})$ 是一个 $m \times s$ 矩阵, $\bm{B}=(b_{ij})$ 是一个 $s \times n$ 矩阵,
那么规定矩阵 $\bm{A}$ 与矩阵 $\bm{B}$ 的乘积是一个 $m \times n$ 的矩阵 $\bm{C}=(c_{ij})$,
其中 \[ c_{ij} = \sum_{k=1}^s a_{ik}j_{kj} \quad (i=1,2,\dots,m; j=1,2,\dots,n) \]
\end{definition}
满足结合律和分配律, 不满足交换律.
- 可交换 :: $\bm{AB} = \bm{BA}$
  \[ \bm{EA} = \bm{AE} = \bm{A} \]
- 纯量阵 :: $\lambda \bm{E} = \diag(\lambda,\lambda,\dots,\lambda)$

** 方阵的幂
\[ \bm{A}^k \bm{A}^l = \bm{A}^{k+l} \qc (\bm{A}^k)^l = \bm{A}^{kl} \]

** 矩阵的转置
\[ (\bm{AB})^{\mathrm{T}} = \bm{B}^{\mathrm{T}} \bm{A}^{\mathrm{T}} \]
- 对称矩阵 :: $\bm{A}^{\mathrm{T}} = \bm{A}$

** 方阵乘积的行列式
\[ |\bm{AB}| = |\bm{A}||\bm{B}| \]
#+begin_proof
设 $\bm{A}=(a_{ij}), \bm{B}=(b_{ij})$. 记四阶行列式 $D = \mdet{\bm{A} & \bm{O} \\ -\bm{E} & \bm{B}}$
\[
D \xlongequal[c_4+b_{12}c_1+b_{22}c_2]{c_3+b_{11}c_1+b_{21}c_2} \mdet{\bm{A} & \bm{X} \\ -\bm{E} & \bm{O}}
= (-1)^2 \mdet{-\bm{E} & \bm{O} \\ \bm{A} & \bm{X}} = |-\bm{E}||\bm{X}| = |\bm{X}| = |\bm{AB}|
\qedhere
\]
#+end_proof

** 伴随矩阵
\[ \bm{A}^{*} = (A_{ij})^{\mathrm{T}} \]
\[ \bm{A} \bm{A}^{*} = \bm{A}^{*} \bm{A} = |\bm{A}| \bm{E} \]

** 逆矩阵的概念和性质
\begin{definition}
对于 $n$ 阶 \uline{方阵} $\bm{A}$, 如果有一个 $n$ 阶 \uline{方阵} $\bm{B}$, 使
\[ \bm{AB} = \bm{BA} = \bm{E} \]
则说矩阵 $\bm{A}$ 是可逆的, 并把矩阵 $\bm{B}$ 称为 $\bm{A}$ 的逆矩阵, 简称逆阵.
\end{definition}

如果矩阵 $\bm{A}$ 是可逆的, 则$\bm{A}$ 的逆矩阵是 _惟一_ 的.

当 $|\bm{A}| = 0$ 时, $\bm{A}$ 称为 _奇异矩阵_, 否则称为 _非奇异矩阵_.

*** 逆矩阵的性质
1. $(\bm{A}^{-1})^{-1}=\bm{A}$.
2. $(\lambda \bm{A})^{-1}=\frac{1}{\lambda}\bm{A}^{-1} \quad (\lambda \neq 0)$.
3. $(\bm{AB})^{-1} = \bm{B}^{-1} \bm{A}^{-1}$ ($\bm{A}, \bm{B}$ 为同阶数的可逆矩阵).
4. $(\bm{A}^{\mathrm{T}})^{-1} = (\bm{A}^{-1})^{\mathrm{T}}$.

*** 逆矩阵的初步应用
设 $\varphi(x) = a_0 + a_1 x + \cdots + a_m x^m$ 为 $x$ 的 $m$ 次多项式, $\bm{A}$ 为 $n$ 阶矩阵, 记
\[ \varphi(\bm{A}) = a_0 \bm{E} + a_1 \bm{A} + \cdots + a_m \bm{A}^m \]
$\varphi(\bm{A})$ 称为矩阵 $\bm{A}$ 的 $m$ 次多项式.

**** $\varphi(\bm{A})$ 的计算方法
1. 若 $\bm{A} = \bm{P\varLambda}\bm{P}^{-1}$, 则 $\bm{A}^k = \bm{P} \bm{\varLambda}^k \bm{P}^{-1}$, 从而
   \[ \varphi(\bm{A}) = \bm{P} \varphi(\bm{\varLambda}) \bm{P}^{-1} \]
2. 如果 $\bm{\varLambda} = \diag(\lambda_1,\lambda_2,\dots,\lambda_n)$ 为对角矩阵, 则 $\bm{\varLambda}^k = \diag(\lambda_1^k,\lambda_2^k,\dots,\lambda_n^k)$, 从而
   \[ \varphi(\bm{\varLambda}) = \mqty(\dmat{\varphi(\lambda_1),\varphi(\lambda_2),\ddots,\varphi(\lambda_n)}) \]

** 矩阵可逆的充分必要条件
$\bm{A}$ 是可逆矩阵的充分必要条件是 $|\bm{A}| \neq 0$, 即可逆矩阵就是非奇异矩阵.

** 分块矩阵及其运算
- 分块矩阵的线性运算和乘法与矩阵的相关运算相似.
- 设 $\bm{A} = \smqty(\bm{A}_{11} & \cdots & \bm{A}_{1r} \\ \vdots & & \vdots \\ \bm{A}_{s1} & \cdots & \bm{A}_{sr})$, 则 $\bm{A}^{\mathrm{T}} = \smqty(\bm{A}_{11}^{\mathrm{T}} & \cdots & \bm{A}_{s1}^{\mathrm{T}} \\ \vdots & & \vdots \\ \bm{A}_{1r}^{\mathrm{T}} & \cdots & \bm{A}_{sr}^{\mathrm{T}})$.

*** 分块对角矩阵
\[ \bm{A} = \mqty(\dmat{\bm{A}_1,\bm{A}_2,\ddots,\bm{A}_s}) \]
其中 $\bm{A}_i \quad (i=1,2,\dots,s)$ 都是方阵.
- $|\bm{A}| = |\bm{A}_1| |\bm{A}_2| \cdots |\bm{A}_s|$.
- 若 $|\bm{A}| \neq 0 \quad (i=1,2,\dots,s)$, 则 $|\bm{A}| \neq 0$, 并有
  \[ \bm{A}^{-1} = \mqty(\dmat{\bm{A}_1^{-1},\bm{A}_2^{-1},\ddots,\bm{A}_s^{-1}}) \]
** 矩阵的初等变换
\begin{definition}[矩阵的初等变换]
初等行变换: \\
1. $r_i \leftrightarrow r_j$ \\
2. $r_i \times k$ \\
3. $r_i+kr_j$ \\
将记号 $r$ 换成 $c$ 即为矩阵的初等列变换, 其与初等行变换统称为初等变换.
\end{definition}

*** 阶梯形、最简形、标准形
\begin{definition}[行阶梯形矩阵]
1. 非零行在零行的上面;
2. 非零行的首非零元所在列在上一行的首非零元的右面.
\end{definition}

\begin{definition}[行最简形矩阵]
1. 非零行的首非零元为1;
2. 首非零元所在的列的其他元均为0,
的行阶梯矩阵
\end{definition}

用归纳法可证: 对于任何非零矩阵 $\bm{A}_{m \times n}$, 总可经有限次初等行变换把它变为行阶梯形矩阵和行最简形矩阵.
- 行阶梯形矩阵中非零行的行数是惟一确定的.
- 一个矩阵的行最简形矩阵是惟一确定的.

\begin{definition}[标准形]
\[ \bm{F} = \mqty(\bm{E}_r & \bm{O} \\ \bm{O} & \bm{O})_{m \times n} \]
\end{definition}

*** 矩阵的等价
- 如果矩阵 $\bm{A}$ 经过有限次初等行变换变成矩阵 $\bm{B}$, 就称矩阵 $\bm{A}$ 与 $\bm{B}$ 行等价, 记作 $\bm{A} \stackrel{r}{\sim} \bm{B}$.
- 如果矩阵 $\bm{A}$ 经过有限次初等列变换变成矩阵 $\bm{B}$, 就称矩阵 $\bm{A}$ 与 $\bm{B}$ 列等价, 记作 $\bm{A} \stackrel{c}{\sim} \bm{B}$.
- 如果矩阵 $\bm{A}$ 经过有限次初等变换变成矩阵 $\bm{B}$, 就称矩阵 $\bm{A}$ 与 $\bm{B}$ 等价, 记作 $\bm{A} \sim \bm{B}$.

矩阵等价的性质:
1. 反身性
2. 对称性
3. 传递性

\begin{theorem}
设 $\bm{A}$ 与 $\bm{B}$ 为 $m \times n$ 矩阵, 那么 \\
1. $\bm{A} \stackrel{r}{\sim} \bm{B} \iff$ 存在可逆矩阵 $\bm{P}_m$, 使 $\bm{PA}=\bm{B}$; \\
2. $\bm{A} \stackrel{c}{\sim} \bm{B} \iff$ 存在可逆矩阵 $\bm{Q}_n$, 使 $\bm{AQ}=\bm{B}$; \\
3. $\bm{A} \sim \bm{B} \iff$ 存在可逆矩阵 $\bm{P}_m,\bm{Q}_n$, 使 $\bm{PAQ}=\bm{B}$.
\end{theorem}

\begin{deduction}
方阵 $\bm{A}$ 可逆的充分必要条件是 $\bm{A} \stackrel{r}{\sim} \bm{E}$.
\end{deduction}

**** 初等矩阵
\begin{definition}
由单位矩阵 $\bm{E}$ 经过一次初等变换得到的矩阵称为初等矩阵.
\end{definition}

初等矩阵的两个重要性质:
1. 设 $\bm{A}_{m \times n}$, 对 $\bm{A}$ 施行一次初等行变换, 相当于 $\bm{A}$ 左乘一个相应的 $m$ 阶初等矩阵.
   对 $\bm{A}$ 施行一次初等列变换, 相当于 $\bm{A}$ 右乘一个相应的 $n$ 阶初等矩阵.
2. 方阵 $\bm{A}$ 可逆的充分必要条件是存在有限个初等矩阵 $\bm{P}_1, \bm{P}_2, \dots, \bm{P}_l$, 使 $\bm{A}=\bm{P}_1\bm{P}_2 \cdots \bm{P}_l$

*** 求线性变换
\begin{equation*}
\bm{PA}=\bm{B} \iff
\begin{cases}
\bm{PA}=\bm{B},\\
\bm{PE}=\bm{P}.
\end{cases}
\iff \bm{P}(\bm{A}, \bm{E}) = (\bm{B}, \bm{P})
\iff (\bm{A},\bm{E}) \stackrel{r}{\sim} (\bm{B},\bm{P})
\end{equation*}

** 矩阵的秩
\begin{definition}
在 $m \times n$ 矩阵 $\bm{A}$ 中, 任取 $k$ 行与 $k$ 列 ($k \leqslant m, k \leqslant n$), 位于这些行列交叉处的 $k^2$ 个元素,
不改变它们在 $\bm{A}$ 中所处的位置次序而得的 $k$ 阶 \uline{行列式}, 称为矩阵 $\bm{A}$ 的 $k$ 阶子式.
\end{definition}

\begin{theorem}
设 $\bm{A} \stackrel{r}{\sim} \bm{B}$, 则 $\bm{A}$ 与 $\bm{B}$ 中非零子式的最高阶数相等.
\end{theorem}

\begin{definition}
设在矩阵 $\bm{A}$ 中有一个不等于 $0$ 的 $r$ 阶子式 $\bm{D}$, 且所有 $r+1$ 阶子式(如果存在的话)全等于 $0$, 那么 $\bm{D}$ 称为矩阵 $\bm{A}$ 的最高阶非零子式,
数 $r$ 称为矩阵 $\bm{A}$ 的秩, 记作 $R(\bm{A})$. 并规定零矩阵的秩等于 $0$.
\end{definition}

可逆矩阵又称 _满秩矩阵_, 不可逆矩阵(奇异矩阵)又称 _降秩矩阵_.

*** 矩阵的秩的性质
1. $0 \leqslant R(\bm{A}_{m \times n}) \leqslant \min \qty{m,n}$.
2. $R(\bm{A}^{\mathrm{T}}) = R(\bm{A})$.
3. 若 $\bm{A} \sim \bm{B}$, 则 $R(\bm{A}) = R(\bm{B})$.
   1. 若 $\bm{P}, \bm{Q}$ 可逆, 则 $R(\bm{PAQ})=R(\bm{A})$.
4. $\max \qty{R(\bm{A}), R(\bm{B})} \leqslant R(\bm{A}, \bm{B}) \leqslant R(\bm{A}) + R(\bm{B})$.
   1. 特别地, 当 $\bm{B}=\bm{b}$ 为非零列向量时, 有 $R(\bm{A}) \leqslant R(\bm{A},\bm{b}) \leqslant R(A)+1$.
5. $R(\bm{A}+\bm{B}) \leqslant R(\bm{A}) + R(\bm{B})$.
6. $R(\bm{AB}) \leqslant \min \qty{R(\bm{A}), R(\bm{B})}$.
7. 若 $\bm{A}_{m \times n} \bm{B}_{n \times l} = \bm{O}$, 则 $R(\bm{A})+R(\bm{B}) \leqslant n$.


- 列满秩矩阵 :: 矩阵的秩数等于它的列数.
- 矩阵乘法的消去律 :: 设 $\bm{AB} = \bm{O}$, 若 $\bm{A}$ 为列满秩矩阵, 则 $\bm{B}=\bm{O}$.

* 向量
** 向量的概念

** 向量的线性组合和线性表示

** 向量组的线性相关与线性无关

** 向量组的极大线性无关组

** 等价向量组

** 向量组的秩

** 向量组的秩与矩阵的秩之间的关系

** 向量的内积

** 线性无关向量组的正交规范化方法

* 线性方程组
** 线性方程组的克拉默(Cramer)法则
含有 $n$ 个未知数 $x_1, x_2, \cdots, x_n$ 的 $n$ 个线性方程的方程组
\begin{equation}
\label{eq:1}
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 ,\\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 ,\\
\cdots \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n = b_n .
\end{cases}
\end{equation}
它的解可以用 $n$ 阶行列式表示, 即有
- 克拉默法则 :: 如果线性方程组 \eqref{eq:1} 的系数矩阵 $\bm{A}$ 的行列式不等于零, 即
  \[ |\bm{A}| = \mdet{a_{11} & \cdots & a_{1n} \\ \vdots & & \vdots \\ a_{n1} & \cdots & a_{nn}} \neq 0 \]
  那么, 该方程组有惟一解
  \[ x_j = \frac{|\bm{A}_j|}{|\bm{A}|} \qc j=1,2,\dots,n \]
  其中 $\bm{A}_j$ 是把系数矩阵 $\bm{A}$ 中第 $j$ 列的元素用方程组右端的常数项代替后所得到的 $n$ 阶矩阵.

** *线性方程组的解
\begin{theorem}
$n$ 元线性方程组 $\bm{Ax}=\bm{b}$ \\
1. 无解 $\iff R(\bm{A}) < R(\bm{A},\bm{b})$; \\
2. 有惟一解 $\iff R(\bm{A})=R(\bm{A},\bm{b})=n$; \\
3. 有无限多解 $\iff R(\bm{A})=R(\bm{A},\bm{b})<n$.
\end{theorem}

** 齐次线性方程组有非零解的充分必要条件
\begin{theorem}
$n$ 元齐次线性方程组 $\bm{Ax}=0$ 有非零解的充分必要条件是 $R(\bm{A})<n$.
\end{theorem}

** 非齐次线性方程组有解的充分必要条件
\begin{theorem}
线性方程组 $\bm{Ax}=\bm{b}$ 有解的充分必要条件是 $R(\bm{A})=R(\bm{A},\bm{b})$.
\end{theorem}

\begin{theorem}
矩阵方程 $\bm{AX}=\bm{B}$ 有解的充分必要条件是 $R(\bm{A}) = R(\bm{A},\bm{B})$.
\end{theorem}

** 线性方程组解的性质和解的结构

** 齐次线性方程组的基础解系和通解

** 非齐次线性方程组的通解

* 矩阵的特征值和特征向量
** 矩阵的特征值和特征向量的概念、性质

** 相似矩阵的概念及性质

** 矩阵可相似对角化的充分必要条件及相似对角矩阵

** 实对称矩阵的特征值、特征向量及其相似对角矩阵

* 二次型

** 二次型及其矩阵表示

** 合同变换与合同矩阵

** 二次型的秩

** 惯性定理

** 二次型的标准形和规范形

** 用正交变换和配方法化二次型为标准形

** 二次型及其矩阵的正定性
