#+LATEX_HEADER: \usepackage{ctex, mathtools, amsthm, booktabs, physics, bm, extarrows}
#+LATEX_HEADER: \usepackage[left=2.5cm, right=2.5cm, top=2cm, bottom=2cm]{geometry}
#+LATEX_HEADER: \usepackage[capitalise, nameinlink]{cleveref}
#+LATEX_HEADER: \hypersetup{colorlinks=true}
#+LATEX_HEADER: \renewcommand\arraystretch{1.5}
#+LATEX_HEADER: \theoremstyle{definition} \newtheorem{definition}{定义}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{theorem}{定理}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem*{deduction}{推论}
#+LATEX_HEADER: \theoremstyle{remark} \newtheorem{remark}{注释}[section]
#+LATEX_HEADER: \DeclareMathOperator{\diag}{diag}
#+LATEX_HEADER: \newcommand{\inner}[2]{[\bm{#1},\bm{#2}]}
#+LATEX_HEADER: \newcommand{\trans}[1]{\bm{#1}^{\mathrm{T}}}

* 行列式
** 行列式的概念和基本性质
*** 排列(Permutation)及其逆序数
\[ P_n^m = n(n-1)(n-2)\cdots(n-m+1) = \frac{n!}{(n-m)!} \]

\[ t = \sum_{i=1}^n t_i \]

*** 对换
\begin{theorem}
一个排列中的任意两个元素对换, 排列改变奇偶性.
\end{theorem}

\begin{deduction}
奇排列对换成标准排列的对换次数为奇数, 偶排列对换成标准排列的对换次数为偶数.
\end{deduction}

*** $n$ 阶行列式(Determinant)
\[ 
D_n = \mdet {
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots &        & \vdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn} \\
}
= \sum_{j_1 j_2 \cdots j_n} (-1)^{\tau(j_1 j_2 \cdots j_n)} a_{1j_1} a_{2j_2} \cdots a_{nj_n}
= \det(a_{ij})
\]

*** 行列式的性质
1. $D=D^{\mathrm{T}}$
2. 对换行列式的两行(列), 行列式变号.
   1. 如果行列式有两行(列)完全相同, 则此行列式等于零.
3. 行列式的某一行(列)中所有的元素都乘同一数 $k$, 等于用数 $k$ 乘此行列式.
   1. 行列式中某一行(列)的所有元素的公因子可以提到行列式记号的外面.
   2. 行列式中如果有两行(列)元素成比例, 则此行列式等于零.
4. 行列式具有分行(列)的可加性.
5. 行列式的某一行(列)中所有元素的 $k$ 倍加到另一行(列)对应的元素上去, 行列式不变.

** 行列式按行(列)展开定理
- 余子式 :: 在 $n$ 阶行列式中, 把 $(i,j)$ 元 $a_{ij}$ 所在的第 $i$ 行和第 $j$ 列划去后, 留下来的 $n-1$ 阶行列式叫做 $(i,j)$ 元 $a_{ij}$ 的余子式, 记作 $M_{ij}$.
- 代数余子式 :: $A_{ij} = (-1)^{i+j} M_{ij}$

\begin{equation*}
\sum_{k=1}^n a_{ki}A_{kj} = 
\begin{cases}
D & i=j. \\
0 & i \neq j.
\end{cases}
\end{equation*}
或
\begin{equation*}
\sum_{k=1}^n a_{ik}A_{jk} = 
\begin{cases}
D & i=j. \\
0 & i \neq j.
\end{cases}
\end{equation*}

* 矩阵
** 矩阵的概念
线性变换和矩阵之间存在着一一对应的关系.
- 对角(Diagonal)矩阵 :: $\bm{\varLambda} = \diag(\lambda_1,\lambda_2,\dots,\lambda_n)$
- 单位矩阵 :: $\bm{E} = \diag(1,1,\dots,1)$

** 矩阵的线性运算
满足交换、结合、分配律.

** 矩阵的乘法
\begin{definition}
设 $\bm{A}=(a_{ij})$ 是一个 $m \times s$ 矩阵, $\bm{B}=(b_{ij})$ 是一个 $s \times n$ 矩阵,
那么规定矩阵 $\bm{A}$ 与矩阵 $\bm{B}$ 的乘积是一个 $m \times n$ 的矩阵 $\bm{C}=(c_{ij})$,
其中 \[ c_{ij} = \sum_{k=1}^s a_{ik}j_{kj} \quad (i=1,2,\dots,m; j=1,2,\dots,n) \]
\end{definition}
满足结合律和分配律, 不满足交换律.
- 可交换 :: $\bm{AB} = \bm{BA}$
  \[ \bm{EA} = \bm{AE} = \bm{A} \]
- 纯量阵 :: $\lambda \bm{E} = \diag(\lambda,\lambda,\dots,\lambda)$

** 方阵的幂
\[ \bm{A}^k \bm{A}^l = \bm{A}^{k+l} \qc (\bm{A}^k)^l = \bm{A}^{kl} \]

** 矩阵的转置
\[ (\bm{AB})^{\mathrm{T}} = \bm{B}^{\mathrm{T}} \bm{A}^{\mathrm{T}} \]
- 对称矩阵 :: $\bm{A}^{\mathrm{T}} = \bm{A}$

** 方阵乘积的行列式
\[ |\bm{AB}| = |\bm{A}||\bm{B}| \]
#+begin_proof
设 $\bm{A}=(a_{ij}), \bm{B}=(b_{ij})$. 记四阶行列式 $D = \mdet{\bm{A} & \bm{O} \\ -\bm{E} & \bm{B}}$
\[
D \xlongequal[c_4+b_{12}c_1+b_{22}c_2]{c_3+b_{11}c_1+b_{21}c_2} \mdet{\bm{A} & \bm{X} \\ -\bm{E} & \bm{O}}
= (-1)^2 \mdet{-\bm{E} & \bm{O} \\ \bm{A} & \bm{X}} = |-\bm{E}||\bm{X}| = |\bm{X}| = |\bm{AB}|
\qedhere
\]
#+end_proof

** 伴随矩阵
\[ \bm{A}^{*} = (A_{ij})^{\mathrm{T}} \]
\[ \bm{A} \bm{A}^{*} = \bm{A}^{*} \bm{A} = |\bm{A}| \bm{E} \]

** 逆矩阵的概念和性质
\begin{definition}
对于 $n$ 阶 \uline{方阵} $\bm{A}$, 如果有一个 $n$ 阶 \uline{方阵} $\bm{B}$, 使
\[ \bm{AB} = \bm{BA} = \bm{E} \]
则说矩阵 $\bm{A}$ 是可逆的, 并把矩阵 $\bm{B}$ 称为 $\bm{A}$ 的逆矩阵, 简称逆阵.
\end{definition}

如果矩阵 $\bm{A}$ 是可逆的, 则$\bm{A}$ 的逆矩阵是 _惟一_ 的.

当 $|\bm{A}| = 0$ 时, $\bm{A}$ 称为 _奇异矩阵_, 否则称为 _非奇异矩阵_.

*** 逆矩阵的性质
1. $(\bm{A}^{-1})^{-1}=\bm{A}$.
2. $(\lambda \bm{A})^{-1}=\frac{1}{\lambda}\bm{A}^{-1} \quad (\lambda \neq 0)$.
3. $(\bm{AB})^{-1} = \bm{B}^{-1} \bm{A}^{-1}$ ($\bm{A}, \bm{B}$ 为同阶数的可逆矩阵).
4. $(\bm{A}^{\mathrm{T}})^{-1} = (\bm{A}^{-1})^{\mathrm{T}}$.

*** 逆矩阵的初步应用
设 $\varphi(x) = a_0 + a_1 x + \cdots + a_m x^m$ 为 $x$ 的 $m$ 次多项式, $\bm{A}$ 为 $n$ 阶矩阵, 记
\[ \varphi(\bm{A}) = a_0 \bm{E} + a_1 \bm{A} + \cdots + a_m \bm{A}^m \]
$\varphi(\bm{A})$ 称为矩阵 $\bm{A}$ 的 $m$ 次多项式.

**** $\varphi(\bm{A})$ 的计算方法
1. 若 $\bm{A} = \bm{P\varLambda}\bm{P}^{-1}$, 则 $\bm{A}^k = \bm{P} \bm{\varLambda}^k \bm{P}^{-1}$, 从而
   \[ \varphi(\bm{A}) = \bm{P} \varphi(\bm{\varLambda}) \bm{P}^{-1} \]
2. 如果 $\bm{\varLambda} = \diag(\lambda_1,\lambda_2,\dots,\lambda_n)$ 为对角矩阵, 则 $\bm{\varLambda}^k = \diag(\lambda_1^k,\lambda_2^k,\dots,\lambda_n^k)$, 从而
   \[ \varphi(\bm{\varLambda}) = \mqty(\dmat{\varphi(\lambda_1),\varphi(\lambda_2),\ddots,\varphi(\lambda_n)}) \]

** 矩阵可逆的充分必要条件
$\bm{A}$ 是可逆矩阵的充分必要条件是 $|\bm{A}| \neq 0$, 即可逆矩阵就是非奇异矩阵.
1. [[jzkn:1][等价]]
2. [[jzkn:2][特征值]]

** 分块矩阵及其运算
- 分块矩阵的线性运算和乘法与矩阵的相关运算相似.
- 设 $\bm{A} = \smqty(\bm{A}_{11} & \cdots & \bm{A}_{1r} \\ \vdots & & \vdots \\ \bm{A}_{s1} & \cdots & \bm{A}_{sr})$, 则 $\bm{A}^{\mathrm{T}} = \smqty(\bm{A}_{11}^{\mathrm{T}} & \cdots & \bm{A}_{s1}^{\mathrm{T}} \\ \vdots & & \vdots \\ \bm{A}_{1r}^{\mathrm{T}} & \cdots & \bm{A}_{sr}^{\mathrm{T}})$.

*** 分块对角矩阵
\[ \bm{A} = \mqty(\dmat{\bm{A}_1,\bm{A}_2,\ddots,\bm{A}_s}) \]
其中 $\bm{A}_i \quad (i=1,2,\dots,s)$ 都是方阵.
1. $|\bm{A}| = |\bm{A}_1| |\bm{A}_2| \cdots |\bm{A}_s|$.
   1. 若 $|\bm{A_i}| \neq 0 \quad (i=1,2,\dots,s)$, 则 $|\bm{A}| \neq 0$, 并有
      \[ \bm{A}^{-1} = \mqty(\dmat{\bm{A}_1^{-1},\bm{A}_2^{-1},\ddots,\bm{A}_s^{-1}}) \]
** 矩阵的初等变换
\begin{definition}[矩阵的初等变换]
初等行变换: \\
1. $r_i \leftrightarrow r_j$ \\
2. $r_i \times k$ \\
3. $r_i+kr_j$ \\
将记号 $r$ 换成 $c$ 即为矩阵的初等列变换, 其与初等行变换统称为初等变换.
\end{definition}

*** 阶梯形、最简形、标准形
\begin{definition}[行阶梯形矩阵]
1. 非零行在零行的上面;
2. 非零行的首非零元所在列在上一行的首非零元的右面.
\end{definition}

\begin{definition}[行最简形矩阵]
1. 非零行的首非零元为1;
2. 首非零元所在的列的其他元均为0,
的行阶梯矩阵
\end{definition}

用归纳法可证: 对于任何非零矩阵 $\bm{A}_{m \times n}$, 总可经有限次初等行变换把它变为行阶梯形矩阵和行最简形矩阵.
- 行阶梯形矩阵中非零行的行数是惟一确定的.
- 一个矩阵的行最简形矩阵是惟一确定的.

\begin{definition}[标准形]
\[ \bm{F} = \mqty(\bm{E}_r & \bm{O} \\ \bm{O} & \bm{O})_{m \times n} \]
\end{definition}

*** 矩阵的等价
- 如果矩阵 $\bm{A}$ 经过有限次初等行变换变成矩阵 $\bm{B}$, 就称矩阵 $\bm{A}$ 与 $\bm{B}$ 行等价, 记作 $\bm{A} \stackrel{r}{\sim} \bm{B}$.
- 如果矩阵 $\bm{A}$ 经过有限次初等列变换变成矩阵 $\bm{B}$, 就称矩阵 $\bm{A}$ 与 $\bm{B}$ 列等价, 记作 $\bm{A} \stackrel{c}{\sim} \bm{B}$.
- 如果矩阵 $\bm{A}$ 经过有限次初等变换变成矩阵 $\bm{B}$, 就称矩阵 $\bm{A}$ 与 $\bm{B}$ 等价, 记作 $\bm{A} \sim \bm{B}$.

矩阵等价的性质:
1. 反身性
2. 对称性
3. 传递性

\begin{theorem}
设 $\bm{A}$ 与 $\bm{B}$ 为 $m \times n$ 矩阵, 那么 \\
1. $\bm{A} \stackrel{r}{\sim} \bm{B} \iff$ 存在可逆矩阵 $\bm{P}_m$, 使 $\bm{PA}=\bm{B}$; \\
2. $\bm{A} \stackrel{c}{\sim} \bm{B} \iff$ 存在可逆矩阵 $\bm{Q}_n$, 使 $\bm{AQ}=\bm{B}$; \\
3. $\bm{A} \sim \bm{B} \iff$ 存在可逆矩阵 $\bm{P}_m,\bm{Q}_n$, 使 $\bm{PAQ}=\bm{B}$.
\end{theorem}

\begin{deduction}
方阵 $\bm{A}$ 可逆的充分必要条件是 $\bm{A} \stackrel{r}{\sim} \bm{E}$.
\end{deduction}
<<jzkn:1>> [[矩阵可逆的充分必要条件]]

**** 初等矩阵
\begin{definition}
由单位矩阵 $\bm{E}$ 经过一次初等变换得到的矩阵称为初等矩阵.
\end{definition}

初等矩阵的两个重要性质:
1. 设 $\bm{A}_{m \times n}$, 对 $\bm{A}$ 施行一次初等行变换, 相当于 $\bm{A}$ 左乘一个相应的 $m$ 阶初等矩阵.
   对 $\bm{A}$ 施行一次初等列变换, 相当于 $\bm{A}$ 右乘一个相应的 $n$ 阶初等矩阵.
2. 方阵 $\bm{A}$ 可逆的充分必要条件是存在有限个初等矩阵 $\bm{P}_1, \bm{P}_2, \dots, \bm{P}_l$, 使 $\bm{A}=\bm{P}_1\bm{P}_2 \cdots \bm{P}_l$

*** 求线性变换
\begin{equation*}
\bm{PA}=\bm{B} \iff
\begin{cases}
\bm{PA}=\bm{B},\\
\bm{PE}=\bm{P}.
\end{cases}
\iff \bm{P}(\bm{A}, \bm{E}) = (\bm{B}, \bm{P})
\iff (\bm{A},\bm{E}) \stackrel{r}{\sim} (\bm{B},\bm{P})
\end{equation*}

** 矩阵的秩
\begin{definition}
在 $m \times n$ 矩阵 $\bm{A}$ 中, 任取 $k$ 行与 $k$ 列 ($k \leqslant m, k \leqslant n$), 位于这些行列交叉处的 $k^2$ 个元素,
不改变它们在 $\bm{A}$ 中所处的位置次序而得的 $k$ 阶 \uline{行列式}, 称为矩阵 $\bm{A}$ 的 $k$ 阶子式.
\end{definition}

\begin{theorem}
设 $\bm{A} \stackrel{r}{\sim} \bm{B}$, 则 $\bm{A}$ 与 $\bm{B}$ 中非零子式的最高阶数相等.
\end{theorem}

\begin{definition}
设在矩阵 $\bm{A}$ 中有一个不等于 $0$ 的 $r$ 阶子式 $\bm{D}$, 且所有 $r+1$ 阶子式(如果存在的话)全等于 $0$, 那么 $\bm{D}$ 称为矩阵 $\bm{A}$ 的最高阶非零子式,
数 $r$ 称为矩阵 $\bm{A}$ 的秩, 记作 $R(\bm{A})$. 并规定零矩阵的秩等于 $0$.
\end{definition}

可逆矩阵又称 _满秩矩阵_, 不可逆矩阵(奇异矩阵)又称 _降秩矩阵_.

*** *矩阵的秩的性质                                                 :drill:
1. $0 \leqslant R(\bm{A}_{m \times n}) \leqslant \min \qty{m,n}$.
2. $R(\bm{A}^{\mathrm{T}}) = R(\bm{A}) = R(\bm{A}\bm{A}^{\mathrm{T}}) = R(\bm{A}^{\mathrm{T}}\bm{A})$.
3. $R(\bm{A}^n) = R(\bm{A}^{n+1})$.
4. 若 $\bm{A} \sim \bm{B}$, 则 $R(\bm{A}) = R(\bm{B})$.
   1. 若 $\bm{P}, \bm{Q}$ 可逆, 则 $R(\bm{PAQ})=R(\bm{A})$.
5. $\max \qty{R(\bm{A}), R(\bm{B})} \leqslant R(\bm{A}, \bm{B}) \leqslant R(\bm{A}) + R(\bm{B})$.
   1. 特别地, 当 $\bm{B}=\bm{b}$ 为非零列向量时, 有 $R(\bm{A}) \leqslant R(\bm{A},\bm{b}) \leqslant R(\bm{A})+1$.
6. $R(\bm{A}+\bm{B}) \leqslant R(\bm{A}) + R(\bm{B})$.
7. $R(\bm{A})+R(\bm{B})-n \leqslant R(\bm{AB}) \leqslant \min \qty{R(\bm{A}), R(\bm{B})} \quad (\bm{A}_{m \times n}, \bm{B}_{n \times l})$.
8. 若 $\bm{A}_{m \times n} \bm{B}_{n \times l} = \bm{O}$, 则 $R(\bm{A})+R(\bm{B}) \leqslant n$.
9. $R(\bm{A}^{*}) = \begin{cases} n & R(\bm{A})=n,\\ 1 & R(\bm{A})=n-1,\\ 0 & R(\bm{A})<n-1. \end{cases}$

#+begin_proof
(2.)即证明齐次方程 $\bm{Ax}= 0$ 与 $(\bm{A}^{\mathrm{T}}\bm{A})\bm{x}= 0$ 同解:
1. 若 $\bm{x}$ 满足 $\bm{Ax}= \bm{0}$, 则有 $\bm{A}^{\mathrm{T}}(\bm{Ax})= \bm{0}$,
   即 $(\bm{A}^{\mathrm{T}})\bm{Ax}= \bm{0}$;
2. 若 $\bm{x}$ 满足 $\bm{A}^{\mathrm{T}}(\bm{Ax})= \bm{0}$, 则 $\bm{x}^{\bm{T}}\bm{A}^{\mathrm{T}}(\bm{Ax})= 0$,
   即 $(\bm{Ax})^{\mathrm{T}}(\bm{Ax})= 0$, 从而 $\bm{Ax}= \bm{0}$.
#+end_proof

- 列满秩矩阵 :: 矩阵的秩数等于它的列数.
- 矩阵乘法的消去律 :: 设 $\bm{AB} = \bm{O}$, 若 $\bm{A}$ 为列满秩矩阵, 则 $\bm{B}=\bm{O}$.

* 向量
** 向量的概念
$n$ 维列向量 \[ \bm{a}=\mqty(a_1 \\ a_2 \\ \vdots \\ a_n) \] 与 
$n$ 维行向量 \[ \bm{a}^{\mathrm{T}}=\qty(a_1, a_2, \dots, a_n) \] 总是看做是两个不同的向量.

- 向量组 :: 若干个同维数的列向量所组成的集合.

** 向量的线性组合和线性表示
\begin{definition}[线性组合]
给定向量组 $A:\bm{a}_1, \bm{a}_2, \dots, \bm{a}_m$ 对于任何一组实数 $k_1, k_2, \dots, k_m$, 表达式
\[k_1\bm{a}_1+k_2\bm{a}_2+ \cdots +k_m\bm{a}_m\]
称为向量组 $A$ 的一个线性组合, $k_1, k_2, \dots, k_m$ 称为这个线性组合的系数.
\end{definition}

\begin{definition}[线性表示]
给定向量组 $A:\bm{a}_1, \bm{a}_2, \dots, \bm{a}_m$ 和向量 $\bm{b}$, 如果存在一组数 $\lambda_1, \lambda_2, \dots, \lambda_m$, 使
\[\bm{b}=\lambda_1\bm{a}_1+\lambda_2\bm{a}_2+\cdots +\lambda_m\bm{a}_m\]
则向量 $\bm{b}$ 是向量组 $A$ 的线性组合, 这是称向量 $\bm{b}$ 能由向量组 $A$ 线性表示.
\end{definition}

\begin{theorem}
向量组 $B$ 能由向量组 $A$ 线性表示的充分必要条件是 $R(\bm{A})=R(\bm{A},\bm{B})$.
\end{theorem}

\begin{theorem}
设向量组 $B$ 能由向量组 $A$ 线性表示, 则 $R(\bm{B}) \leqslant R(\bm{A})$.
\end{theorem}

** 等价向量组
\begin{definition}[向量组等价]
设有两个向量组 $A:\bm{a}_1, \bm{a}_2, \dots, \bm{a}_m$ 及 $B:\bm{b}_1,\bm{b}_2,\dots,\bm{b}_l$, 若 $B$ 组中的每个向量都能由向量组 $A$ 线性表示,
则称向量组 $B$ 能由向量组 $A$ 线性表示. 若向量组 $A$ 与向量组 $B$ 能相互线性表示, 则称这两个向量组等价.
\end{definition}

\begin{deduction}
向量组 $A$ 与向量组 $B$ 等价的充分必要条件是 \[R(\bm{A})=R(\bm{B})=R(\bm{A},\bm{B})\]
\end{deduction}

** 向量组的线性相关与线性无关
\begin{definition}
给定向量组 $A:\bm{a}_1, \bm{a}_2, \dots, \bm{a}_m$, 如果存在不全为零的数 $k_1, k_2, \dots, k_m$, 使
\[k_1\bm{a}_1+k_2\bm{a}_2+ \cdots +k_m\bm{a}_m = 0\]
则称向量组 $A$ 是线性相关的, 否则称它线性无关.
\end{definition}

\begin{theorem}
向量组 $A:\bm{a}_1, \bm{a}_2, \dots, \bm{a}_m$ 线性相关的充分必要条件是它所构成的矩阵 
$\bm{A}=(\bm{a}_1, \bm{a}_2, \dots, \bm{a}_m)$ 的秩小于向量个数 $m$; \\
向量组 $A$ 线性无关的充分必要条件是 $R(\bm{A})=m$.
\end{theorem}
即齐次方程有无穷多解(非零解) $\iff$ 其有效方程个数少于未知数个数.

*** *线性相关的一些结论
1. 一个向量组若含有线性相关的部分组, 则该向量组线性相关. 反之, 一个向量组若线性无关, 则它的任何部分组都线性无关.
2. $m$ 个 $n$ 维向量组成的向量组, 当维数 $n$ 小于向量个数 $m$ 时一定线性相关.
3. 设列向量组 $A$ 线性无关, 而向量组 $(A,\bm{b})$ 线性相关, 则 $\bm{b}$ 必能由向量组 $A$ 线性表示, 且表达式是惟一的.

** 向量组的秩
\begin{definition}
设有向量组 $A$, 如果在 $A$ 中能选出 $r$ 个向量 $\bm{a}_1,\bm{a}_2, \dots, \bm{a}_r$, 满足 \\
1. 向量组 $A_0:\bm{a}_1, \bm{a}_2, \dots, \bm{a}_r$ 线性无关; \\
2. 向量组 $A$ 中任意 $r+1$ 个向量都线性相关, \\
那么称向量组 $A_0$ 是向量组 $A$ 的一个最大线性无关向量组, 其所含向量个数 $r$ 称为向量组 $A$ 的秩, 记作 $R_A$.
\end{definition}

*** 向量组的极大线性无关组
向量组 $A$ 和它自己的最大无关组 $A_0$ 是等价的.

\begin{deduction}[最大无关组的等价定义]
设列向量组 $A_0$ 是向量组 $A$ 的一个部分组, 且满足 \\
1. 向量组 $A_0$ 线性无关; \\
2. 向量组 $A$ 的任一向量都能由向量组 $A_0$ 线性表示, \\
那么向量组 $A_0$ 便是向量组 $A$ 的一个最大无关组.
\end{deduction}

** 向量组的秩与矩阵的秩之间的关系
\begin{theorem}
矩阵的秩等于它的列向量组的秩, 也等于它的行向量组的秩.
\end{theorem}

- 齐次方程组同解 ::  如果矩阵 $\bm{A}_{m \times n}, \bm{B}_{l \times n}$ 的行向量组等价
  (此时 $\bm{Ax}= \bm{0}$ 与 $\bm{Bx}= \bm{0}$ 可互推), 则方程 $\bm{Ax}= \bm{0}$ 与 $\bm{Bx}= \bm{0}$ 同解.
  从而两个方程的列向量组之间的线性关系相同.

* 线性方程组
** 线性方程组的克拉默(Cramer)法则
含有 $n$ 个未知数 $x_1, x_2, \dots, x_n$ 的 $n$ 个线性方程的方程组
\begin{equation}
\label{eq:1}
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 ,\\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 ,\\
\cdots \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n = b_n .
\end{cases}
\end{equation}
它的解可以用 $n$ 阶行列式表示, 即有
- 克拉默法则 :: 如果线性方程组 eqref:eq:1 的系数矩阵 $\bm{A}$ 的行列式不等于零, 即
  \[ |\bm{A}| = \mdet{a_{11} & \cdots & a_{1n} \\ \vdots & & \vdots \\ a_{n1} & \cdots & a_{nn}} \neq 0 \]
  那么, 该方程组有惟一解
  \[ x_j = \frac{|\bm{A}_j|}{|\bm{A}|} \qc j=1,2,\dots,n \]
  其中 $\bm{A}_j$ 是把系数矩阵 $\bm{A}$ 中第 $j$ 列的元素用方程组右端的常数项代替后所得到的 $n$ 阶矩阵.

** *线性方程组的解
\begin{theorem}
$n$ 元线性方程组 $\bm{Ax}=\bm{b}$ \\
1. 无解 $\iff R(\bm{A}) < R(\bm{A},\bm{b})$; \\
2. 有惟一解 $\iff R(\bm{A})=R(\bm{A},\bm{b})=n$; \\
3. 有无限多解 $\iff R(\bm{A})=R(\bm{A},\bm{b})<n$.
\end{theorem}

** 齐次线性方程组有非零解的充分必要条件
\begin{theorem}
$n$ 元齐次线性方程组 $\bm{Ax}=0$ 有非零解的充分必要条件是 $R(\bm{A})<n$.
\end{theorem}

** 非齐次线性方程组有解的充分必要条件
\begin{theorem}
线性方程组 $\bm{Ax}=\bm{b}$ 有解的充分必要条件是 $R(\bm{A})=R(\bm{A},\bm{b})$.
\end{theorem}

\begin{theorem}
矩阵方程 $\bm{AX}=\bm{B}$ 有解的充分必要条件是 $R(\bm{A}) = R(\bm{A},\bm{B})$.
\end{theorem}

** 线性方程组解的性质和解的结构
*** 齐次线性方程组的基础解系和通解
对于向量方程 $\bm{Ax}=\bm{0}$:
1. 若 $\bm{x}=\bm{\xi}_1,x=\bm{\xi}_2$ 为该方程的解, 则 $\bm{x}=\bm{\xi}_1+\bm{\xi}_2$ 也是该方程的解.
2. 若 $\bm{x}=\bm{\xi}_1$ 为该方程的解, $k$ 为实数, 则 $x=k\bm{\xi}_1$ 也是该方程的解.

齐次线性方程组的解集的最大无关组 $S_0:\bm{\xi}_1,\bm{\xi}_2,\dots,\bm{\xi}_t$ 称为该齐次线性方程组的 _基础解系_. \\
则该方程的解的 _通解_ 即为 $\bm{x}=k_1\bm{\xi}_1+k_2\bm{\xi}_2+\cdots+k_t\bm{\xi}_t$.

\begin{theorem}
设矩阵 $\bm{A}_{m \times n}$ 的秩 $R(\bm{A})=r$, 则 $n$ 元齐次线性方程组 $\bm{Ax}=\bm{0}$ 的解集 $S$ 的秩 $R_s=n-r$.
\end{theorem}

*** 非齐次线性方程组的通解
对于向量方程 $\bm{Ax}=\bm{b}$:
1. 设 $\bm{x}=\bm{\eta}_1,\bm{x}=\bm{\eta}_2$ 都是该方程的解, 则 $x=\bm{\eta}_1-\bm{\eta}_2$ 为对应的齐次线性方程组 $\bm{Ax}=0$ 的解.
2. 设 $\bm{x}=\bm{\eta}$ 是该方程的解, $\bm{x}=\bm{\xi}$ 是对应的齐次方程的解, 则 $\bm{x}=\bm{\xi}+\bm{\eta}$ 仍是该方程的解.

若求得该方程的 _特解_ 为 $\bm{\eta}^{*}$, 那么其 _通解_ 为 $\bm{x}=k_1\bm{\xi}_1+\cdots+k_{n-r}\bm{\xi}_{n-r}+\bm{\eta}^{*}$.

* 矩阵的特征值和特征向量

** 向量的内积
\begin{definition}
设有 $n$ 维向量
\[\bm{x}=\mqty(x_1\\x_2\\\vdots\\x_n),\bm{y}=\mqty(y_1\\y_2\\\vdots\\y_n)\]
令
\[[\bm{x},\bm{y}]=x_1y_1+x_2y_2+\cdots +x_ny_n\]
$\inner{x}{y}$ 称为向量 $\bm{x}$ 与 $\bm{y}$ 的 \uline{内积}.
\end{definition}

当 $x$ 与 $y$ 都是列向量时, 有
\[\inner{x}{y}=\bm{x}^{\mathrm{T}}\bm{y}\]

内积满足交换律, 结合律, 分配律.

\begin{theorem}[施瓦茨(Schwarz) 不等式]
\[\inner{x}{y}\leqslant\inner{x}{x}\inner{y}{y}\]
\end{theorem}

\begin{definition}
令
\[\norm{x}=\sqrt{\inner{x}{x}}\]
称为 $n$ 维向量 $\bm{x}$ 的 \uline{长度} 或 \uline{范数}.
\end{definition}

向量的长度具有非负性和齐次性.

- 单位向量 :: $\norm{x}=1$

\begin{definition}[向量的夹角]
\[\theta=\arccos \frac{\inner{x}{y}}{\norm{x}\norm{y}} \quad \bm{x}\neq 0,y\neq 0\]
\end{definition}

- 正交 :: $\inner{x}{y}=0$
- 正交向量组 :: 一组两两正交的非零向量.

\begin{theorem}
正交向量组必线性无关.
\end{theorem}

** 线性无关向量组的正交规范化方法
\begin{definition}
设 $n$ 维向量 $\bm{e}_1,\bm{e}_2,\dots,\bm{e}_r$ 是向量空间 $V (V \subseteq \mathbb{R}^n)$ 的一个基,
如果 $\bm{e}_1,\dots,\bm{e}_r$ 两两正交, 且都是单位向量, 则称 $\bm{e}_1,\dots,\bm{e}_r$ 是 $V$ 的一个 \uline{标准正交基}.
\end{definition}

$V$ 中任一向量 $\bm{a}$ 应能由 $\bm{e}_1,\dots,\bm{e}_r$ 线性表示, 设表达式为
\[\bm{a}=\lambda_1\bm{e}_1+\lambda_2\bm{e}_2+ \cdots +\lambda_r\bm{e}_r\]
为求其中的系数 $\lambda_i (i=1,\dots,r)$, 可用 $\bm{e}_i^{\mathrm{T}}$ 左乘上式, 有
\[\bm{e}_i^{\mathrm{T}}\bm{a}=\lambda_i\bm{e}_i^{\mathrm{T}}\bm{e}_i=\lambda_i\]
即
\[\lambda_i=\bm{e}_i^{\mathrm{T}}\bm{a}=[\bm{a},\bm{e}_i]\]

*** 施密特(Schmidt) 正交化
设 $\bm{a}_1,\dots,\bm{a}_r$ 是向量空间 $V$ 中的一个基, 要求 $V$ 的一个标准正交基.
这也就是要找一组两两正交的单位向量 $\bm{e}_1,\dots,\bm{e}_r$ 使 $\bm{e}_1,\dots,\bm{e}_r$ 与 $\bm{a}_1,\dots,\bm{a}_r$ 等价. 取
\begin{align*}
\bm{b}_1 &= \bm{a}_1, \\
\bm{b}_2 &= \bm{a}_2 - \frac{[\bm{b}_1,\bm{a}_2]}{[\bm{b}_1,\bm{b}_1]}\bm{b}_1, \\
\cdots \\
\bm{b}_r &= \bm{a}_r - \frac{[\bm{b}_1,\bm{a}_r]}{[\bm{b}_1,\bm{b}_1]}\bm{b}_1 - \frac{[\bm{b}_2,\bm{a}_r]}{[\bm{b}_2,\bm{b}_2]}\bm{b}_2 - \cdots - 
\frac{[\bm{b}_{r-1},\bm{a}_r]}{[\bm{b}_{r-1},\bm{b}_{r-1}]}\bm{b}_{r-1}
\end{align*}
容易验证 $\bm{b}_1,\dots,\bm{b}_r$ 两两正交, 且 $\bm{a}_1,\dots,\bm{a}_r$ 与 $\bm{b}_1,\dots,\bm{b}_r$ 等价,
且对任何 $k(1\leqslant k\leqslant r)$, 向量组 $\bm{a}_1,\dots,\bm{a}_k$ 与 $\bm{b}_1,\dots,\bm{b}_k$ 等价.
然后把它们单位化, 即取
\[\bm{e}_i=\frac{\bm{b}_i}{\norm{\bm{b}_i}} (i=1,\dots,r)\]
就是 $V$ 的一个标准正交基.

- $\bm{a}$ 在 $\bm{b}$ 上的投影 ::
\begin{equation*}
\qty[\bm{a},\frac{\bm{b}}{\norm{\bm{b}}}]\frac{\bm{b}}{\norm{\bm{b}}}=\frac{\inner{a}{b}}{\norm{\bm{b}}^2}\bm{b}
\end{equation*}

** 正交矩阵和正交变换
\begin{definition}[正交矩阵]
如果 $n$ 阶矩阵 $\bm{A}$ 满足
\[\bm{A}^{\mathrm{T}}\bm{A}=\bm{E}(\text{即}\bm{A}^{-1}=\bm{A}^{\mathrm{T}})\]
那么称 $\bm{A}$ 为正交矩阵, 简称正交阵.
\end{definition}

用列向量表示即为
\begin{equation*}
\bm{a}_i^{\mathrm{T}}\bm{a}_j=
\begin{cases}
1 & i=j,\\
0 & i\neq j.
\end{cases}
\quad (i,j=1,2,\dots,n)
\end{equation*}

即方阵 $\bm{A}$ 为正交矩阵 $\iff \bm{A}$ 的列(行)向量都是单位向量, 且两两正交.

*** 正交矩阵的性质
1. 若 $\bm{A}$ 为正交矩阵, 则 $\bm{A}^{-1}=\bm{A}^{\mathrm{T}}$ 也是正交矩阵, 且 $|\bm{A}|=1 \text{或} (-1)$.
2. 若 $\bm{A}, \bm{B}$ 都为正交矩阵, 则 $\bm{AB}$ 也是正交矩阵.

\begin{definition}[正交变换]
若 $\bm{P}$ 为正交矩阵, 则线性变换 $\bm{y}=\bm{Px}$ 称为正交变换.
\end{definition}

设 $\bm{y}= \bm{Px}$ 为正交变换, 则有
\[ \norm{\bm{y}}= \sqrt{\bm{y}^{\mathrm{T}}\bm{y}}= \sqrt{\bm{x}^{\mathrm{T}}\bm{P}^{\mathrm{T}}\bm{Px}}= \sqrt{\bm{x}^{\mathrm{T}}\bm{x}}= \norm{\bm{x}} \]

** 矩阵的特征值和特征向量的概念、性质
\begin{definition}
设 $\bm{A}$ 是 $n$ 阶矩阵, 如果数 $\lambda$ 和 $n$ 维非零列向量 $x$ 使关系式
\[ \bm{Ax} = \lambda \bm{x}\]
成立, 那么, 这样的数称为矩阵 $\bm{A}$ 的特征值, 非零向量 $\bm{x}$ 称为 $\bm{A}$ 的对应于特征值 $\lambda$ 的特征向量.
\end{definition}
即 $(\bm{A}-\lambda \bm{E})\bm{x}=0$

- 特征方程 :: $|\bm{A}-\lambda \bm{E}|=0$
- 特征多项式 :: $f(\lambda)=|\bm{A}-\lambda \bm{E}|$

*** 特征值的性质
设 $n$ 阶矩阵 $\bm{A}=(a_{ij})$ 的特征值为 $\lambda_1,\lambda_2,\dots,\lambda_n$, 不难证明[fn:1]:
1. $\lambda_1+\lambda_2+\cdots+\lambda_n=a_{11}+a_{22}+\cdots +a_{nn}$;
2. $\lambda_1\lambda_2\cdots\lambda_n=|\bm{A}|$.
   1. $\bm{A}$ 可逆的充分必要条件是它的特征值不含零. <<jzkn:2>> [[矩阵可逆的充分必要条件]]

设 $\lambda$ 是 $\bm{A}$ 的特征值, 则
1. $\lambda^k$ 是 $\bm{A}^k$ 的特征值;
2. $\varphi(\lambda)$ 是 $\varphi(\bm{A})$ 的特征值
   (其中 $\varphi(\lambda)=a_0+ a_1\lambda+\cdots+a_m\lambda^m$ 是 $\lambda$ 的多项式,
   $\varphi(\bm{A})=a_0\bm{E}+a_1\bm{A}+\cdots+a_m\bm{A}^m$ 是矩阵 $\bm{A}$ 的多项式).

\begin{theorem}
设 $\lambda_1, \lambda_2, \dots, \lambda_m$ 是方阵 $\bm{A}$ 的 $m$ 个特征值, $\bm{p}_1,\bm{p}_2,\dots,\bm{p}_m$ 依次是与之对应的特征向量,
如果 $\lambda_1, \lambda_2, \dots, \lambda_m$ 各不相等, 则 $\bm{p}_1,\bm{p}_2,\dots,\bm{p}_m$ 线性无关.
\end{theorem}

\begin{deduction}
设 $\lambda_1$ 和 $\lambda_2$ 是方阵 $\bm{A}$ 的两个不同特征值, $\bm{\xi}_1,\bm{\xi}_2,\dots,\bm{\xi}_s$ 和 $\bm{\eta}_1,\bm{\eta}_2,\dots,\bm{\eta}_t$
分别是对应于 $\lambda_1$ 和 $\lambda_2$ 的线性无关的特征向量, 则 $\bm{\xi}_1,\bm{\xi}_2,\dots,\bm{\xi}_s, \bm{\eta}_1,\bm{\eta}_2,\dots,\bm{\eta}_t$ 线性无关.
\end{deduction}
#+begin_proof
留作习题?
#+end_proof
上述推论表明: 对应于两个不同特征值的线性无关的特征向量组, 合起来仍是线性无关的. 这一结论对 $m(\geqslant 2)$ 个特征值的情形也成立.

** 相似矩阵的概念及性质
\begin{definition}
设 $\bm{A}$ 和 $\bm{B}$ 都是 $n$ 阶矩阵, 若有可逆矩阵 $\bm{P}$, 使
\[ \bm{P}^{-1}\bm{AP} = \bm{B} \]
则称 $\bm{B}$ 是 $\bm{A}$ 的相似矩阵, 或说矩阵 $\bm{A}$ 与 $\bm{B}$ 相似.
对 $\bm{A}$ 进行运算 $\bm{P}^{-1}\bm{AP}$ 称为对 $\bm{A}$ 进行相似变换,
可逆矩阵 $\bm{P}$ 称为把 $\bm{A}$ 变成 $\bm{B}$ 的相似变换矩阵.
\end{definition}

\begin{theorem}
若 $n$ 阶矩阵 $\bm{A}$ 与 $\bm{B}$ 相似, 则 $\bm{A}$ 与 $\bm{B}$ 的特征多项式相同, 从而 $\bm{A}$ 与 $\bm{B}$ 的特征值亦相同.
\end{theorem}

\begin{deduction}
若 $n$ 阶矩阵 $\bm{A}$ 与对角矩阵
\[ \bm{\varLambda} = \diag(\lambda_1, \lambda_2, \dots, \lambda_n) \]
相似, 则 $\lambda_1, \lambda_2, \dots, \lambda_n$ 即是 $\bm{\varLambda}$ 的 $n$ 个特征值.
\end{deduction}

** 矩阵可相似对角化的充分必要条件及相似对角矩阵
\begin{theorem}
$n$ 阶矩阵 $\bm{A}$ 与对角矩阵相似(即 $\bm{A}$ 能对角化) 的充分必要条件是 $\bm{A}$ 由 $n$ 个线性无关的特征向量.
\end{theorem}

\begin{deduction}
如果 $n$ 阶矩阵 $\bm{A}$ 的 $n$ 个特征值互不相等, 则 $\bm{A}$ 与对角矩阵相似.
\end{deduction}

** 实对称矩阵的特征值、特征向量及其相似对角矩阵
- 对称矩阵的特征值为实数.
- 设 $\lambda_1, \lambda_2$ 是对称矩阵 $\bm{A}$ 的两个特征值, $\bm{p}_1,\bm{p}_2$ 是对应的特征向量.
  若 $\lambda_1 \neq \lambda_2$, 则 $\bm{p}_1$ 与 $\bm{p}_2$ 正交.

\begin{theorem}
\label{thr:1}
设 $\bm{A}$ 为 $n$ 阶对称矩阵, 则必有正交矩阵 $\bm{P}$, 使 $\bm{P}^{-1}\bm{AP} = \bm{P}^{\mathrm{T}}\bm{AP} = \bm{\varLambda}$,
其中 $\bm{\varLambda}$ 是以 $\bm{A}$ 的 $n$ 个特征值为对角元的对角矩阵.
\end{theorem}
#+begin_proof
#+end_proof

\begin{deduction}
设 $\bm{A}$ 为 $n$ 阶对称矩阵, $\lambda$ 是 $\bm{A}$ 的特征方程的 $k$ 重根, 则矩阵 $\bm{A}-\lambda \bm{E}$ 的秩 $R(\bm{A}-\lambda \bm{E})= n-k$,
从而对应特征值 $\lambda$ 恰有 $k$ 个线性无关的特征向量.
\end{deduction}

*** 对称矩阵对角化的步骤
1. 求出 $\bm{A}$ 的全部互不相等的特征值 $\lambda_1, \dots, \lambda_s$, 它们的重数依次为 $k_1,\dots,k_s \quad (k_1+\cdots+k_s=n)$.
2. 对每个 $k_i$ 重特征值 $\lambda_i$, 求方程 $(\bm{A}-\lambda_i \bm{E})x = 0$ 的基础解系, 得 $k_i$ 个线性无关的特征向量.
   再把它们正交化、单位化, 得 $k_i$ 个两两正交的单位特征向量.
   因 $k_1+\cdots+k_s=n$, 故总共可得 $n$ 个两两正交的单位特征向量.
3. 把这 $n$ 个两两正交的单位特征向量构成正交矩阵 $\bm{P}$, 便有 $\bm{P}^{-1}\bm{AP}= \bm{P}^{\mathrm{T}}\bm{AP}= \bm{\varLambda}$.
   注意 $\bm{\varLambda}$ 中对角元的排列次序应与 $\bm{P}$ 中列向量的排列次序相对应.

* 二次型
** 二次型及其矩阵表示
\begin{definition}[二次型]
含有 $n$ 个变量 $x_1,x_2,\dots,x_n$ 的二次齐次函数
\begin{align*}
f(x_1,x_2,\dots,x_n) ={} & a_{11}x_1^2+a_{22}x_2^2+\cdots+a_{nn}x_n^2+ \\
& 2a_{12}x_1x_2+2a_{13}x_1x_3+\cdots+2a_{n-1,n}x_{n-1}x_n \\
={} & \sum_{i,j=1}^n a_{ij}x_ix_j \quad (a_{ji}=a_{ij}) \\
={} & \bm{x}^{\mathrm{T}}\bm{Ax}
\end{align*}
称为二次型.
\end{definition}

** 二次型的标准形和规范形
- 二次型的标准形(法式) :: \[ f=k_1y_1^2+k_2y_2^2+\cdots+k_ny_n^2 \]
- 二次型的规范形 :: \[ f=y_1^2+\cdots+y_p^2-y_{p+1}^2-\cdots-y_r^2 \quad (p+r\leqslant n) \]

** 二次型的秩
二次型与其对称矩阵 $\bm{A}$ 之间存在一一对应的关系.
对称矩阵 $\bm{A}$ 的秩就叫做 _二次型 $f$ 的秩_.

** 合同变换与合同矩阵
记对二次型做的可逆变换为 \[\bm{x} = \bm{Cy}\]
则有 $f=\bm{x}^{\mathrm{T}}\bm{Ax} = (\bm{Cy})^{\mathrm{T}}\bm{ACy} = \bm{y}^{\mathrm{T}}(\bm{C}^{\mathrm{T}}\bm{AC})\bm{y}$.

\begin{definition}[合同]
设 $\bm{A}$ 和 $\bm{B}$ 是 $n$ 阶矩阵, 若有可逆矩阵 $\bm{C}$, 使
\[ \bm{B} = \bm{C}^{\mathrm{T}}\bm{AC} \]
则称矩阵 $\bm{A}$ 与 $\bm{B}$ 合同.
\end{definition}
若 $\bm{A}$ 为对称矩阵, 则 $\bm{B} = \bm{C}^{\mathrm{T}}\bm{AC}$ 也为对称矩阵, 且 $R(\bm{B}) = R(\bm{A})$.
经可逆变换 $\bm{x} = \bm{Cy}$ 后, 二次型 $f$ 的矩阵由 $\bm{A}$ 变为与 $\bm{A}$ 合同的矩阵 $\bm{C}^{\mathrm{T}}\bm{AC}$, 且二次型的秩不变.

** 用正交变换和配方法化二次型为标准形
- 合同对角化 :: 对于对称矩阵 $\bm{A}$, 寻求可逆矩阵 $\bm{C}$, 使 $\bm{C}^{\mathrm{T}}\bm{AC}$ 为对角矩阵.

由 cref:thr:1 知, 任给对称矩阵 $\bm{A}$, 总有正交矩阵 $\bm{P}$, 使 $\bm{P}^{-1}\bm{AP} = \bm{\varLambda}$,
即 $\bm{P}^{\mathrm{T}}\bm{AP} = \bm{\varLambda}$. 由此
\begin{theorem}
\label{thr:2}
任给二次型 $f=\sum\limits_{i,j=1}^n a_{ij}x_ix_j \quad (a_{ji}=a_{ij})$, 总有正交变换 $\bm{x} = \bm{Py}$, 使 $f$ 化为标准形
\[ f=\lambda_1y_1^2+\lambda_2y_2^2+\cdots+\lambda_ny_n^2 \]
其中 $\lambda_1,\lambda_2,\dots,\lambda_n$ 是 $f(\bm{Cz})$ 的矩阵 $\bm{A}= (a_{ij})$ 的特征值.
\end{theorem}

\begin{deduction}
任给 $n$ 元二次型 $f(\bm{x})= \bm{x}^{\mathrm{T}}\bm{Ax} (\bm{A}^{\mathrm{T}}=\bm{A})$, 总有可逆变换 $\bm{x}=\bm{Cz}$,
使 $f(\bm{Cz})$ 为规范形.
\end{deduction}

#+begin_proof
由 cref:thr:2, 有
\[ f(\bm{Py})=\bm{y}^{\mathrm{T}}\bm{\varLambda y}=\lambda_1y_1^2+\cdots+\lambda_ny_n^2 \]
设二次型 $f$ 的秩为 $r$, 则特征值 $\lambda_i$ 中恰有 $r$ 个不为 $0$, 不妨设 $\lambda_1,\dots,\lambda_r \neq 0$,
$\lambda_{r+1},\dots,\lambda_n = 0$, 令
\[ \bm{K}=\diag(k_1,k_2,\dots,k_n) \]
其中
\begin{equation*}
k_i=
\begin{cases}
\frac{1}{\sqrt{\abs{\lambda_i}}} & i \leqslant r,\\
1 & i>r.
\end{cases}
\end{equation*}
则 $\bm{K}$ 可逆, 变换 $\bm{y}=\bm{Kz}$ 把 $f(\bm{Py})$ 化为
\[ f(\bm{PKz})=\trans{z}\trans{K}\trans{P}\bm{APKz}=\trans{z}\trans{K}\bm{\varLambda Kz} \]
而
\[ \trans{K}\bm{\varLambda K} = \diag(\frac{\lambda_1}{\abs{\lambda_1}},\dots,\frac{\lambda_r}{\abs{\lambda_r}},0,\dots,0) \]
记 $\bm{C}=\bm{PK}$, 即知可逆变换 $x=\bm{Cz}$ 把 $f$ 化成规范形
\[ f(\bm{Cz})=\frac{\lambda_1}{\abs{\lambda_1}}z_1^2+\cdots+\frac{\lambda_r}{\abs{\lambda_r}}z_r^2 \qedhere \]
#+end_proof

** 惯性定理

** 二次型及其矩阵的正定性

* Footnotes

[fn:1] $f(\lambda) = (\lambda_1-\lambda)(\lambda_2-\lambda)\cdots(\lambda_n-\lambda)$, 其中 $\lambda^0$ 和 $\lambda^{n-1}$ 的系数分别为
$\lambda_1\lambda_2\cdots\lambda_n$ 和 $(-1)^{n-1}(\lambda_1+\lambda_2+\cdots+\lambda_n)$,
故只需证明多项式 $|\bm{A}-\lambda \bm{E}|$ 中 $\lambda^0$ 和 $\lambda^{n-1}$ 的系数依次为 $|\bm{A}|$ 和 $(-1)^{n-1}(a_{11}+a_{22}+\cdots+a_{nn})$.
