#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{ctex, mathtools, amsthm, booktabs, physics}
#+LATEX_HEADER: \renewcommand\arraystretch{1.5}
#+LATEX_HEADER: \theoremstyle{definition} \newtheorem{definition}{定义}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{theorem}{定理}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{deduction}{推论}[section]
#+LATEX_HEADER: \theoremstyle{remark} \newtheorem{remark}{注释}[section]
#+STARTUP: align

* DONE 函数、极限、连续
CLOSED: [2019-09-23 Mon 21:45]
** 函数的概念及表示法
#+begin_quote
理解函数的概念, 掌握函数的表示法, 会建立应用问题的函数关系.
#+end_quote

*** 函数的概念
设 $x$ 与 $y$ 是两个变量, 变量 $x$ 的取值范围是非空数集 $D$, 如果对 $D$ 中任意一个 $x$, 
变量 $y$ 按照一定的法则总有 *唯一* 的数值与之对应, 则称变量 $y$ 是变量 $x$ 的函数. 记为
\[
y=f(x) \qq{或} y=y(x)
\]
其中 $x$ 称为自变量, $y$ 称为因变量, $D$ 称为函数 $y=f(x)$ 的定义域.

*** 函数的表示法
- 列表法
- 图像法
- 解析法

** 函数的有界性、单调性、周期性和奇偶性
#+begin_quote
了解函数的有界性、单调性、周期性和奇偶性.
#+end_quote

*** 有界性
设函数 $f(x)$ 的定义域为 $D$, $I \subset D$, 如果存在正数 $M$, 使得对任意 $x \in I$, 
都有 $\abs{f(x)} \leqslant M$, 则称函数 $f(x)$ 在 $I$ 上有界. 如果这样的 $M$ 不存在, 
则称函数 $f(x)$ 在 $I$ 上无界.
 
** 复合函数、反函数、分段函数和隐函数
#+begin_quote
理解复合函数及分段函数的概念, 了解反函数及隐函数的概念.
#+end_quote

*** 分段函数
**** 狄利克雷(Dirichlet)函数
\[
D(x)=\lim _{k \to \infty}\left(\lim _{j \to \infty}(\cos (k ! \pi x))^{2 j}\right)
\]

** 基本初等函数的性质及其图形
#+begin_quote
掌握基本初等函数的性质及其图形, 了解初等函数的概念.
#+end_quote

*** 基本初等函数
**** 常值函数
**** 幂函数
**** 指数函数
**** 对数函数
**** 三角函数
**** 反三角函数

** 初等函数
由基本初等函数经过有限次四则运算或有限次复合运算而得到的, 并且可以用一个数学式子表示的函数, 称为初等函数.

** 函数关系的建立

** 数列极限与函数极限的定义及其性质
#+begin_quote
理解极限的概念, 理解函数左极限与右极限的概念以及函数极限存在与左极限、右极限之间的关系.
#+end_quote
*** 数列极限的定义
\begin{definition}
给定数列 ${x_n}$, $a$ 为常数, 如果对于任意 $\varepsilon > 0$, 存在正整数 $N$, 当 $n>N$ 时, 有
\[
\abs{x_n-a} <\varepsilon
\]
则称数列 ${x_n}$ 以 $a$ 为极限, 或称数列 ${x_n}$ 收敛于 $a$, 记为
\[
\lim_{n \to \infty} x_n = a \qq{或} x_n \to a (n \to \infty)
\]
\end{definition}

*** 收敛数列的性质
**** 唯一性
**** 有界性
**** 保号性
**** 一致性
\begin{theorem}[收敛数列与其子数列的关系]
如果数列 ${x_n}$ 收敛于 $a$, 那么它的任一子数列也收敛, 且极限也是 $a$.
\end{theorem}

*** 函数极限的定义
#+CAPTION: 函数极限的定义
#+ATTR_LATEX: :float nil :booktabs t :center t
|                 | $f(x) \to A$                                                                 |
|-----------------+------------------------------------------------------------------------------|
| $x \to x_0$     | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<\abs{x-x_0}<\delta$ 时 |
| $x \to x_{0^+}$ | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<x-x_0<\delta$ 时       |
| $x \to x_{0^-}$ | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0>x-x_0>-\delta$ 时      |
| $x \to \infty$  | $\forall \varepsilon >0$, $\exists X>0$, 使当 $\abs{x}>X$ 时                 |
| $x \to +\infty$ | $\forall \varepsilon >0$, $\exists X>0$, 使当 $x>X$ 时                       |
| $x \to -\infty$ | $\forall \varepsilon >0$, $\exists X>0$, 使当 $x<-X$ 时                      |
|-----------------+------------------------------------------------------------------------------|
|                 | 即有 $\abs{f(x)-A}<\varepsilon$                                              |

*** 函数极限的性质
**** 唯一性

**** 局部有界性
\begin{theorem}
若 $\lim f(x) = A$, 则存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x)$ 有界.
\end{theorem}
(对于 $x \to x_0$, $\mathring{U}$ 表示 $0<\abs{x-x_0}<\delta$; 对于 $x \to \infty$, $\mathring{U}$ 表示 $\abs{x}>X$)

**** 局部保号性
\begin{theorem}
若 $\lim f(x) = A>B$, 则存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x)>B$.
\end{theorem}

\begin{deduction}
若存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x) \geqslant B$, 且 $\lim f(x) = A$, 则 $A \geqslant B$.
\end{deduction}

**** 一致性
\begin{theorem}[函数极限与数列极限的关系]
如果极限 $\lim_{x \to x_0}f(x)$ 存在, ${x_n}$ 为函数 $f(x)$ 的定义域内任一收敛于 $x_0$ 的数列,
且满足: $x_n \neq x_0 (n \in N_+)$, 那么相应的函数值数列 ${f(x_n)}$ 必收敛, 且 $\lim_{n \to +\infty} f(x_n) = \lim_{x \to x_0} f(x)$.
\end{theorem}

** 函数的左极限和右极限
[[函数极限的定义]]

** 无穷小量和无穷大量大概念及其关系
#+begin_quote
理解无穷小量、无穷大量的概念, 掌握无穷小量的比较方法, 会用等价无穷小量求极限.
#+end_quote
*** 无穷小量与极限的关系
\[
\lim_{x \to x_0} f(x) = A \Leftrightarrow A + \alpha(x)
\]
其中 $\lim_{x \to x_0} \alpha(x) = 0$.

** 无穷小量的性质及无穷小量的比较
*** 无穷小量的比较
若 $\lim \dfrac{\beta}{\alpha^k}=c \neq 0 \quad (k>0)$, 称 $\beta$ 是 $\alpha$ 的 $k$ 阶无穷小量.

** 极限的四则运算
#+begin_quote
掌握极限的性质及四则运算法则.
#+end_quote
设 $\lim f(x)$ 存在, $\lim g(x)$ 不存在, 则 $\lim[f(x) \pm g(x)]$ 不存在.

** 极限存在的两个准则：单调有界准则和夹逼准则
#+begin_quote
掌握极限存在的两个法则, 并会利用它们求极限, 掌握利用两个重要极限求极限的方法.
#+end_quote
*** 单调有界准则
若数列 ${x_n}$ 单调增加(或单调减少)且有上界 $M$ (或有下界 $m$ ), 则 $x_n$ 收敛,
且 $\lim_{n \to \infty} x_n \leqslant M$(或 $\lim_{n \to \infty} x_n \geqslant m$).

*** 夹逼准则
设三个数列满足 $y_n \leqslant x_n \leqslant z_n$, 且 $\lim_{n \to \infty} y_n = \lim_{n \to \infty} z_n = a$, 则 $\lim_{n \to \infty} x_n = a$.

夹逼准则对于函数极限也成立.

** 两个重要极限
\[
\lim_{x \to 0} \frac{\sin x}{x} = 1
\]
\[
\lim_{x \to 0} (1+x)^{\frac{1}{x}} = \lim_{x \to \infty}\left( 1+\frac{1}{x} \right)^x = e
\]

** 函数连续的概念
#+begin_quote
理解函数连续性的概念(含左连续与右连续), 会判别函数间断点的类型.
#+end_quote
设函数 $y=f(x)$ 在点 $x_0$ 的某一领域内有定义, 极限 $\lim_{x \to x_0}f(x)$ 存在, 且 $\lim_{x \to x_0}f(x) = f(x_0)$,
则称函数 $y=f(x)$ 在点 $x_0$ 处连续, 并称 $x_0$ 是 $f(x)$ 的连续点.

** 函数间断点的类型
- 可去间断点
- 跳跃间断点
- 无穷间断点
- 振荡间断点

** 初等函数的连续性
#+begin_quote
了解连续函数的性质和初等函数的连续性, 理解闭区间上连续函数的性质(有界性、最大值和最小值定理、介值定理), 并会应用这些性质.
#+end_quote
一切初等函数在其定义区间内都连续.

** 闭区间上连续函数的性质
设 $f(x)$ 在 $[a,b]$ 上连续, 则
1. (有界性定理) $f(x)$ 在 $[a,b]$ 上有界.
2. (最值定理) 存在 $\xi_1, \xi_2 \in [a,b]$, 使 \[ f(\xi_1) = M = \max_{x \in [a,b]}f(x), \quad f(\xi_2) = m = \min_{x \in [a,b]} f(x) \]
3. (介值定理) 对于任意 $\mu: m \leqslant \mu \leqslant M$, 存在 $\xi \in [a,b]$, 使 $f(\xi)=\mu$.
特别地, 若 $f(a)f(b)<0$, 则存在 $\xi \in (a,b)$, 使 $f(\xi)=0$.

* TODO 一元函数微分学
** 导数和微分的概念

** 导数的几何意义和物理意义

** 函数的可导性与连续性之间的关系

** 平面曲线的切线和法线

** 导数和微分的四则运算

** 基本初等函数的导数
\begin{align*}
  (\arcsin x)' &= \frac{1}{\sqrt{1-x^2}} & (\arctan x)' &= \frac{1}{1+x^2}  \\
  (\arccos x)' &= -\frac{1}{\sqrt{1-x^2}} & (\arccot x)' &= -\frac{1}{1+x^2}
\end{align*}

** 复合函数、反函数、隐函数以及参数方程所确定的函数的微分法

** 高阶导数

** 一阶微分形式的不变性

** 微分中值定理
*** 泰勒公式
\[
f(x)=\sum_{n=0}^{N} \frac{f^{(n)}(a)}{n !}(x-a)^{n} + R_n(x)
\]

- 拉格朗日余项 :: $R_n(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-a)^{n+1}$, $\xi$ 介于 $x$ 和 $a$ 之间.

- 佩亚诺余项 :: $R_n(x)=o(x^n)$

#+CAPTION: 几个常用的麦克劳林展开式
#+ATTR_LATEX: :float nil :booktabs t :center t
| $f(x)$     | $=$ | $f(0)$ | $f'(0)x$ | $\frac{f''(0)}{2!}x^2$ | $\frac{f'''(0)}{3!}x^3$     | $\cdots$ | $\frac{f^{(n)}(0)}{n!}x^n$            | $R_n(x)$      |
|------------+-----+--------+----------+------------------------+-----------------------------+----------+---------------------------------------+---------------|
| $e^x$      | $=$ | $1$    | $x$      | $\frac{1}{2!}x^2$      | $\frac{1}{3!}x^3$           | $\cdots$ | $\frac{1}{n!}x^n$                     | $o(x^n)$      |
| $\sin{x}$  | $=$ |        | $x$      |                        | $-\frac{1}{3!}x^3$          | $\cdots$ | $(-1)^{n-1}\frac{1}{(2n-1)!}x^{2n-1}$ | $o(x^{2n})$   |
| $\cos{x}$  | $=$ | $1$    |          | $-\frac{1}{2!}x^2$     |                             | $\cdots$ | $(-1)^n\frac{1}{(2n)!}x^{2n}$         | $o(x^{2n+1})$ |
| $\ln(1+x)$ | $=$ |        | $x$      | $-\frac{1}{2}x^2$      | $\frac{1}{3}x^3$            | $\cdots$ | $(-1)^{n-1}\frac{1}{n}x^n$            | $o(x^n)$      |
| $(1+x)^m$  | $=$ | $1$    | $mx$     | $\frac{m(m-1)}{2!}x^2$ | $\frac{m(m-1)(m-2)}{3!}x^3$ | $\cdots$ | $\frac{m(m-1)\dots(m-n+1)}{n!}x^n$    | $o(x^n)$      |

** 洛必达(L' Hospital)法则

** 函数单调性的判别

** 函数的极值

** 函数图形的凹凸性、拐点及渐近线

** 函数图形的描绘

** 函数的最大值与最小值

** 弧微分

** 曲率的概念

** 曲率圆与曲率半径

* TODO 一元函数积分学
** 原函数和不定积分的概念

** 不定积分的基本性质

** 基本积分公式
\begin{align*}
  \int \sec ^{2} x \dd{x} &= \tan x+C & \int \sec x \dd{x} &= \ln \abs{\sec x+\tan x} + C \\
  \int \csc ^{2} x \dd{x} &= -\cot x+C & \int \csc x \dd{x} &= \ln \abs{\csc x-\cot x} + C \\
  \\
  \int \frac{1}{\sqrt{a^2-x^2}} \dd{x} &= \arcsin \frac{x}{a} + C 
                                      & \int \frac{1}{a^2+x^2} \dd{x} &= \frac{1}{a} \arctan \frac{x}{a} + C \\
  \int \frac{1}{\sqrt{x^2 \pm a^2}} \dd{x} &= \ln \abs{x+\sqrt{x^2 \pm a^2}} + C
                                      & \int \frac{1}{a^2-x^2} \dd{x} &= \frac{1}{2a} \ln \abs{\frac{a+x}{a-x}} + C \\
\end{align*}

** 定积分的概念和基本性质

** 定积分中值定理

** 积分上限的函数及其导数

** 牛顿-莱布尼兹(Newton-Leibniz)公式

** 不定积分和定积分的换元积分法与分部积分法
*** 分部积分法
设 $u=u(x)$, $v=v(x)$ 均有连续的导数, 则
\[
\int u \dd{v} = uv -\int v \dd{u}
\]

** 有理函数、三角函数的有理式和简单无理函数的积分

** 反常(广义)积分

** 定积分的应用

* TODO 多元函数微积分学
** 多元函数的概念

** 二元函数的几何意义

** 二元函数的极限与连续的概念

** 有界闭区域上二元连续函数的性质

** 多元函数的偏导数和全微分

** 多元复合函数、隐函数的求导法

** 二阶偏导数

** 多元函数的极值和条件极值、最大值和最小值

** 二重积分的概念、基本性质和计算

* TODO 常微分方程
** 常微分方程的基本概念

** 变量可分离的微分方程

** 齐次微分方程

** 一阶线性微分方程

** 可降阶的高阶微分方程

** 线性微分方程解的性质及解的结构定理

** 二阶常系数齐次线性微分方程

** 简单的二阶常系数非齐次线性微分方程

** 微分方程的简单应用
