#+LATEX_HEADER: \usepackage{mathtools, amsthm, booktabs, physics}
#+LATEX_HEADER: \renewcommand\arraystretch{1.5}
#+LATEX_HEADER: \theoremstyle{definition} \newtheorem{definition}{定义}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{theorem}{定理}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem*{deduction}{推论}
#+LATEX_HEADER: \theoremstyle{remark} \newtheorem{remark}{注释}[section]
#+LATEX_HEADER: \DeclareMathOperator{\lcm}{lcm}

* 函数、极限、连续
1. 理解函数的概念, 掌握函数的表示法, 会建立应用问题的函数关系.
2. 了解函数的有界性、单调性、周期性和奇偶性.
3. 理解复合函数及分段函数的概念, 了解反函数及隐函数的概念.
4. 掌握基本初等函数的性质及其图形, 了解初等函数的概念.
5. 理解极限的概念, 理解函数左极限与右极限的概念以及函数极限存在与左极限、右极限之间的关系.
6. 理解无穷小量、无穷大量的概念, 掌握无穷小量的比较方法, 会用等价无穷小量求极限.
7. 掌握极限的性质及四则运算法则.
8. 掌握极限存在的两个法则, 并会利用它们求极限, 掌握利用两个重要极限求极限的方法.
9. 理解函数连续性的概念(含左连续与右连续), 会判别函数间断点的类型.
10. 了解连续函数的性质和初等函数的连续性, 理解闭区间上连续函数的性质(有界性、最大值和最小值定理、介值定理), 并会应用这些性质.

** 函数的概念及表示法
*** 函数的概念
设 $D \subset \mathbf{R}$, 则称映射 $f:D \to \mathbf{R}$ 为定义在 $D$ 上的函数, 通常简记为
\[ y=f(x), x \in D \]

*** 函数的表示法
- 列表法
- 图像法
- 解析法

** 函数的有界性、单调性、周期性和奇偶性
*** 有界性
设函数 $f(x)$ 的定义域为 $D$, $I \subset D$, 如果存在正数 $M$, 使得对任意 $x \in I$, 
都有 $\abs{f(x)} \leqslant M$, 则称函数 $f(x)$ 在 $I$ 上有界. 如果这样的 $M$ 不存在, 
则称函数 $f(x)$ 在 $I$ 上无界.

*** 奇偶性
- $f(x)$ 是可导的奇(偶)函数, 则 $f'(x)$ 是偶(奇)函数.
- $f(x)$ 是连续的奇函数, 则其所有原函数都是偶函数.
- $f(x)$ 是连续的偶函数, 则其所有原函数中只有一个是奇函数($\int_0^x f(x)\,\mathrm{d}x$).
- $f(x)+f(-x)$ 是偶函数，$f(x)-f(-x)$ 是奇函数.
  - 任意一个函数可以写成偶函数与奇函数的和的形式.

** 复合函数、反函数、分段函数和隐函数
*** 分段函数
**** 狄利克雷(Dirichlet)函数
\[
D(x)=\lim _{k \to \infty}\left(\lim _{j \to \infty}(\cos (k ! \pi x))^{2 j}\right)
\]

** 基本初等函数的性质及其图形
*** 基本初等函数
**** 常值函数
**** 幂函数
**** 指数函数
**** 对数函数
**** 三角函数
\begin{align*}
\sin(A+B) &= \sin(A) \cos(B) + \cos(A) \sin(B) \\
\cos(A+B) &= \cos(A) \cos(B) - \sin(A) \sin(B)
\end{align*}

***** 倍角公式
\begin{align*}
\sin 2x &= 2 \sin x \cos x \\
\cos 2x &= \cos^2 x - \sin^2 x \\
&= 2 \cos^2 x - 1 \\
&= 1 - 2\sin^2 x
\end{align*}

***** 降幂公式
\begin{align*}
\sin^2 x &= \frac{1}{2} (1 - \cos 2x) \\
\cos^2 x &= \frac{1}{2} (1 + \cos 2x)
\end{align*}

***** 半角公式
\[
\tan \frac{x}{2} = \frac{1-\cos x}{\sin x} = \frac{\sin x}{1+\cos x}
\]

:hint:
分式上下同乘 $\sin \frac{x}{2}$ 或 $\cos \frac{x}{2}$.
:END:

**** 反三角函数

** 初等函数
由基本初等函数经过有限次四则运算或有限次复合运算而得到的, 并且可以用一个数学式子表示的函数, 称为初等函数.
*** 双曲函数
\begin{align*}
\sinh x &= \frac{e^x-e^{-x}}{2} \\
\cosh x &= \frac{e^x+e^{-x}}{2}
\end{align*}

\begin{align*}
\sinh(x+y) &= \sinh x \cosh y + \cosh x \sinh y \\
\cosh(x+y) &= \cosh x \cosh y + \sinh x \sinh y
\end{align*}

*** 反双曲函数
\begin{align*}
\asin x &= \ln(x+\sqrt{x^2+1}) \qc x \in (- \infty, + \infty) \\
\acos x &= \ln(x+\sqrt{x^2-1}) \qc x \in [1, + \infty) \\
\atan x &= \frac{1}{2} \ln \frac{1+x}{1-x} \qc x \in (-1,1)
\end{align*}

** 函数关系的建立
** 数列极限与函数极限的定义及其性质
*** 数列极限的定义
\begin{definition}
给定数列 ${x_n}$, $a$ 为常数, 如果对于任意 $\varepsilon > 0$, 存在正整数 $N$, 当 $n>N$ 时, 有
\[
\abs{x_n-a} <\varepsilon
\]
则称数列 ${x_n}$ 以 $a$ 为极限, 或称数列 ${x_n}$ 收敛于 $a$, 记为
\[
\lim_{n \to \infty} x_n = a \qq{或} x_n \to a (n \to \infty)
\]
\end{definition}

*** 收敛数列的性质
**** 唯一性
**** 有界性
**** 保号性
**** 一致性
\begin{theorem}[收敛数列与其子数列的关系]
如果数列 ${x_n}$ 收敛于 $a$, 那么它的任一子数列也收敛, 且极限也是 $a$.
\end{theorem}

*** 函数极限的定义
\begin{definition}
设函数 $f(x)$ 在点 $x_0$ 的某去心邻域内有定义, A 为一个常数, 如果对于任意 $\varepsilon > 0$, 存在 $\delta > 0$,
使得当 $0<\abs{x-x_0}<\delta$ 时, 有 
\[ \abs{f(x)-A}<\varepsilon \]
则称函数 $f(x)$ 当 $x \to x_0$ 时以 $A$ 为极限, 记为
\[ \lim_{x \to x_0} f(x) = A \qq{或} f(x) \to A \quad (x \to x_0) \]
\end{definition}

#+CAPTION: 函数极限的定义
#+ATTR_LATEX: :float nil :booktabs t :center t
|                 | $\lim f(x) = A$                                                              |
|-----------------+------------------------------------------------------------------------------|
| $x \to x_0$     | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<\abs{x-x_0}<\delta$ 时 |
| $x \to x_{0^+}$ | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<x-x_0<\delta$ 时       |
| $x \to x_{0^-}$ | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<x_0-x<\delta$ 时       |
| $x \to \infty$  | $\forall \varepsilon >0$, $\exists X>0$, 使当 $\abs{x}>X$ 时                 |
| $x \to +\infty$ | $\forall \varepsilon >0$, $\exists X>0$, 使当 $x>X$ 时                       |
| $x \to -\infty$ | $\forall \varepsilon >0$, $\exists X>0$, 使当 $x<-X$ 时                      |
|-----------------+------------------------------------------------------------------------------|
|                 | 有 $\abs{f(x)-A}<\varepsilon$                                                |

*** 函数极限的性质
**** 唯一性

**** 局部有界性
\begin{theorem}
若 $\lim f(x) = A$, 则存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x)$ 有界.
\end{theorem}
(对于 $x \to x_0$, $\mathring{U}$ 表示 $0<\abs{x-x_0}<\delta$; 对于 $x \to \infty$, $\mathring{U}$ 表示 $\abs{x}>X$)

**** 局部保号性
\begin{theorem}
若 $\lim f(x) = A>B$, 则存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x)>B$.
\end{theorem}

\begin{deduction}
若存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x) \geqslant B$, 且 $\lim f(x) = A$, 则 $A \geqslant B$.
\end{deduction}

**** 一致性
\begin{theorem}[函数极限与数列极限的关系]
如果极限 $\lim_{x \to x_0}f(x)$ 存在, ${x_n}$ 为函数 $f(x)$ 的定义域内任一收敛于 $x_0$ 的数列,
且满足: $x_n \neq x_0 (n \in N_+)$, 那么相应的函数值数列 ${f(x_n)}$ 必收敛, 且 $\lim_{n \to +\infty} f(x_n) = \lim_{x \to x_0} f(x)$.
\end{theorem}

** 函数的左极限和右极限
[[函数极限的定义]]

** 无穷小量和无穷大量大概念及其关系
*** 无穷小量与极限的关系
\[
\lim_{x \to x_0} f(x) = A \Leftrightarrow A + \alpha(x)
\]
其中 $\lim_{x \to x_0} \alpha(x) = 0$.

** 无穷小量的性质及无穷小量的比较
*** 无穷小量的比较
若 $\lim \dfrac{\beta}{\alpha^k}=c \neq 0 \quad (k>0)$, 称 $\beta$ 是 $\alpha$ 的 $k$ 阶无穷小量.

** 极限的四则运算
设 $\lim f(x)$ 存在, $\lim g(x)$ 不存在, 则 $\lim[f(x) \pm g(x)]$ 不存在.

** 极限存在的两个准则：单调有界准则和夹逼准则
*** 单调有界准则
若数列 ${x_n}$ 单调增加(或单调减少)且有上界 $M$ (或有下界 $m$ ), 则 $x_n$ 收敛,
且 $\lim_{n \to \infty} x_n \leqslant M$(或 $\lim_{n \to \infty} x_n \geqslant m$).

*** 夹逼准则
设三个数列满足 $y_n \leqslant x_n \leqslant z_n$, 且 $\lim_{n \to \infty} y_n = \lim_{n \to \infty} z_n = a$, 则 $\lim_{n \to \infty} x_n = a$.

夹逼准则对于函数极限也成立.

** 两个重要极限
\[
\lim_{x \to 0} \frac{\sin x}{x} = 1
\]
\[
\lim_{x \to 0} (1+x)^{\frac{1}{x}} = \lim_{x \to \infty}\left( 1+\frac{1}{x} \right)^x = e
\]

** 函数连续的概念
设函数 $y=f(x)$ 在点 $x_0$ 的某一领域内有定义, 极限 $\lim_{x \to x_0}f(x)$ 存在, 且 $\lim_{x \to x_0}f(x) = f(x_0)$,
则称函数 $y=f(x)$ 在点 $x_0$ 处连续, 并称 $x_0$ 是 $f(x)$ 的连续点.

** 函数间断点的类型
*** 第一类间断点
$f(x_0 + 0)$ 与 $f(x_0 - 0)$ 都存在
- 可去间断点 :: $f(x_0 + 0) = f(x_0 - 0)$
- 跳跃间断点 :: $f(x_0 + 0) \neq f(x_0 - 0)$
*** 第二类间断点
$f(x_0 + 0)$ 与 $f(x_0 - 0)$ 至少有一个不存在
- 无穷间断点 :: $f(x_0 + 0)$ 与 $f(x_0 - 0)$ 至少有一个为 $\infty$
- 振荡间断点 :: $f(x_0 + 0)$ 与 $f(x_0 - 0)$ 至少有一个上下振荡

** 初等函数的连续性
一切初等函数在其定义区间内都连续.

** 闭区间上连续函数的性质
设 $f(x)$ 在 $[a,b]$ 上连续, 则
1. (有界性定理) $f(x)$ 在 $[a,b]$ 上有界.
2. (最值定理) 存在 $\xi_1, \xi_2 \in [a,b]$, 使 \[ f(\xi_1) = M = \max_{x \in [a,b]}f(x), \quad f(\xi_2) = m = \min_{x \in [a,b]} f(x) \]
3. (介值定理) 对于任意 $\mu: m \leqslant \mu \leqslant M$, 存在 $\xi \in [a,b]$, 使 $f(\xi)=\mu$.
特别地, 若 $f(a)f(b)<0$, 则存在 $\xi \in (a,b)$, 使 $f(\xi)=0$.

* 一元函数微分学
1. 理解导数和微分的概念, 理解导数与微分的关系, 理解导数的几何意义, 会求平面曲线的切线方程和法线方程, 了解导数的物理意义, 会用导数描述一些物理量, 理解函数的可导性与连续性之间的关系.
2. 掌握导数的四则运算法则和复合函数的求导法则, 掌握基本初等函数的导数公式. 了解微分的四则运算法则和一阶微分形式的不变性, 会求函数的微分.
3. 了解高阶导数的概念, 会求简单函数的高阶导数.
4. 会求分段函数的导数, 会求隐函数和有参数方程所确定的函数以及反函数的导数.
5. 理解并会用罗尔(Rolle)定理、拉格朗日(Lagrange)中值定理和泰勒(Taylor)定理, 了解并会用柯西(Cauchy)中值定理.
6. 掌握用洛必达法则求未定式极限的方法.
7. 理解函数的极值概念, 掌握用导数判断函数的单调性和求函数极值的方法, 掌握函数最大值和最小值的求法及其应用.
8. 会用导数判断函数图形的凹凸性, 会求函数图形的拐点以及水平、铅直和斜渐近线, 会描绘函数的图形.
9. 了解曲率、曲率圆与曲率半径的概念, 会计算曲率和曲率半径.

** 导数和微分的概念
*** 导数的定义
\begin{definition}
设函数 $f(x)$ 在 $U(x_0)$ 内有定义, 若极限
\[ \lim_{\Delta x \to 0} \frac{\Delta y}{\Delta x} = \lim_{\Delta x \to 0} \frac{f(x_0+\Delta x) - f(x_0)}{\Delta x} \]
存在, 则称函数 $f(x)$ 在点 $x=x_0$ 处可导,并称这个极限为 $f(x)$ 在点 $x_0$ 处的导数,
记为 $f'(x_0)$ 或 $\eval{\dv{y}{x}}_{x=x_0}$ 等.
\end{definition}

导数定义的等价形式:
\[
f'(x_0) = \lim_{h \to 0} \frac{f(x_0)+h - f(x_0)}{h} = \lim_{x \to x_0} \frac{f(x) - f(x_0)}{x - x_0}
\]

*** 微分的定义
\begin{definition}
设函数 $f(x)$ 在 $U(x_0)$ 内有定义, $x_0+\Delta x \in U(x_0)$, 如果
\[ \Delta y = f(x_0+\Delta x) - f(x_0) = A \Delta x + o(\Delta x), \]
则称函数 $f(x)$ 在点 $x=x_0$ 处可微,
称 $\dd{y} = A \Delta x$ 为 $f(x)$ 在点 $x=x_0$ 处的微分.
\end{definition}

** 导数的几何意义和物理意义
** 函数的可导性与连续性之间的关系
可导 $\Rightarrow$ 连续

** 平面曲线的切线和法线
** 导数和微分的四则运算
** 基本初等函数的导数
\begin{align*}
  (\arcsin x)' &= \frac{1}{\sqrt{1-x^2}} & (\arctan x)' &= \frac{1}{1+x^2}  \\
  (\arccos x)' &= -\frac{1}{\sqrt{1-x^2}} & (\arccot x)' &= -\frac{1}{1+x^2}
\end{align*}

** 复合函数、反函数、隐函数以及参数方程所确定的函数的微分法
*** 复合函数的导数
\begin{align*}
{f[g(x)]}' &= \dv{\{f[g(x)]\}}{x} \\
f'[g(x)] &= \dv{\{f[g(x)]\}}{[g(x)]}
\end{align*}

** 高阶导数
*** 运算法则

**** 莱布尼茨(Leibniz)公式
\[
(uv)^{(n)} = \sum_{k=0}^n \mathrm{C}_n^k u^{(n-k)} v^{(k)}
\]

:remarks:
可以参考二项式定理(binomial theorem):
\[
(x+y)^n = \sum_{k=0}^n \mathrm{C}_n^k x^{n-k} y^k
\]
其中 $\mathrm{C}_n^k = \frac{n!}{k!(n-k)!}$
:END:

*** 常用的 $n$ 阶导数公式
\begin{align*}
(\sin x)^{(n)} &= \sin(x+\frac{n \pi}{2}) & \left( \frac{1}{ax+b} \right)^{(n)} &= (-1)^n \frac{a^n n!}{(ax+b)^{n+1}} \\
(\cos x)^{(n)} &= \cos(x+\frac{n \pi}{2}) & [\ln(ax+b)]^{(n)} &= (-1)^{n-1} \frac{a^n (n-1)!}{(ax+b)^n}
\end{align*}

*** 由参数方程所确定的函数的二阶导数
设 $\begin{cases} x=x(t), \\ y=y(t). \end{cases}$ $x(t)$ 和 $y(t)$ 可导, 且 $x'(t) \neq 0$, 则
\[
\dv[2]{y}{x} = \dv{t}(\frac{y'_t}{x'_t}) \dv{t}{x} = \frac{y''_{tt} x'_t - y'_t x''_{tt}}{(x'_t)^3}
\]

*** 反函数的二阶导数
设 $y=f(x)$ 二阶可导, 记 $f'(x) = y'_x$, 记其反函数 $x=\varphi(y)$ 的导数 $\varphi'(y) = x'_y \neq 0$, 则有
\[
y''_{xx} = \dv[2]{y}{x} = \dv{\dv{y}{x}}{x} = \dv{\frac{1}{x'_y}}{y} \dv{y}{x} = - \frac{x''_{yy}}{(x'_y)^2} \frac{1}{x'_y} = 
-\frac{x''_{yy}}{(x'_y)^3}
\]

** 一阶微分形式的不变性
对 $y=f(u)$, 不论 $u$ 是自变量还是中间变量, 均有 $\dd{y} = f'(u) \dd{u}$.

** 微分中值定理
*** 费马(Fermat)定理
\begin{theorem}[费马引理]
设函数 $f(x)$ 在点 $x_0$ 的某领域 $U(x_0)$ 内有定义, 并且在 $x_0$ 处可导, 如果对任意的 $x \in U(x_0)$, 有
$f(x) \leqslant f(x_0)$ (或 $f(x) \geqslant f(x_0)$), 则 $f'(x_0) = 0$.
\end{theorem}

*** 罗尔(Rolle)定理
\begin{theorem}
设 $f(x)$ 在 $[a,b]$ 上连续, 在 $(a,b)$ 内可导, 且 $f(a)=f(b)$, 则存在 $\xi \in (a,b)$, 使
\[ f'(\xi) = 0 \]
\end{theorem}

*** 拉格朗日(Lagrange)中值定理
\begin{theorem}
设 $f(x)$ 在 $[a,b]$ 上连续, 在 $(a,b)$ 内可导, 则存在 $\xi \in (a,b)$, 使
\[ f(b)-f(a) = f'(\xi)(b-a) \]
\end{theorem}

*** 柯西(Cauchy)中值定理
\begin{theorem}
设 $f(x), g(x)$ 在 $[a,b]$ 上连续, 在 $(a,b)$ 内可导, 且 $g'(x) \neq 0$, 则存在 $\xi \in (a,b)$, 使
\[ \frac{f(b)-f(a)}{g(b)-g(a)} = \frac{f'(\xi)}{g'(\xi)} \]
\end{theorem}

*** 泰勒(Taylor)公式                                                :drill:
SCHEDULED: <2019-10-25 Fri>
:PROPERTIES:
:ID:       D9A7C860-C44E-478F-A5B6-95FE36F5A6A1
:DRILL_LAST_INTERVAL: 3.86
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 3.0
:DRILL_EASE: 2.36
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2019-10-21 Mon 19:42]
:END:
\[
f(x)=\sum_{n=0}^N \frac{f^{(n)}(a)}{n!}(x-a)^n + R_n(x)
\]

- 拉格朗日余项 :: $R_n(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-a)^{n+1}$, $\xi$ 介于 $x$ 和 $a$ 之间.

- 佩亚诺(Peano)余项 :: $R_n(x)=o(x^n)$

#+CAPTION: 几个常用的麦克劳林(Maclaurin)展开式 (省略余项)
#+ATTR_LATEX: :float nil :booktabs t :center t
|    $f(x)$    | $f(0)$ | $f'(0)x$ | $\frac{f''(0)}{2!}x^2$ |   $\frac{f'''(0)}{3!}x^3$   |                    $n^{\mathrm{th}}$                     |
|--------------+--------+----------+------------------------+-----------------------------+----------------------------------------------------------|
|      /       |   <    |          |                        |              >              |                            <                             |
|     <c>      |  <c>   |   <c>    |          <c>           |             <c>             |                           <c>                            |
|    $e^x$     |  $1$   |   $x$    |   $\frac{1}{2!}x^2$    |      $\frac{1}{3!}x^3$      |                    $\frac{1}{n!}x^n$                     |
|  $\cos{x}$   |  $1$   |          |   $-\frac{1}{2!}x^2$   |                             |              $(-1)^n\frac{1}{(2n)!}x^{2n}$               |
|  $\sin{x}$   |        |   $x$    |                        |     $-\frac{1}{3!}x^3$      |          $(-1)^{n-1}\frac{1}{(2n-1)!}x^{2n-1}$           |
| $\arcsin{x}$ |        |   $x$    |                        |      $\frac{1}{3!}x^3$      |               $\frac{1}{(2n-1)!}x^{2n-1}$                |
|  $\tan{x}$   |        |   $x$    |                        |      $\frac{1}{3}x^3$       | $(-1)^{n-1}\frac{2^{2n}(2^{2n}-1)B_{2n}}{(2n)!}x^{2n-1}$ |
| $\arctan{x}$ |        |   $x$    |                        |      $-\frac{1}{3}x^3$      |              $(-1)^n\frac{1}{2n-1}x^{2n-1}$              |
|  $\ln(1+x)$  |        |   $x$    |   $-\frac{1}{2}x^2$    |      $\frac{1}{3}x^3$       |                $(-1)^{n-1}\frac{1}{n}x^n$                |
|  $(1+x)^m$   |  $1$   |   $mx$   | $\frac{m(m-1)}{2!}x^2$ | $\frac{m(m-1)(m-2)}{3!}x^3$ |            $\frac{m(m-1)\dots(m-n+1)}{n!}x^n$            |

[[http://mathworld.wolfram.com/MaclaurinSeries.html][其他公式查询]]

** 洛必达(L' Hospital)法则
设在自变量的同一变化过程中, $\lim f(x) = 0 (\text{或} \infty)$, $\lim g(x) = 0 (\text{或} \infty)$,
且 $f(x), g(x)$ 可导, $g'(x) \neq 0$, $\lim \frac{f'(x)}{g'(x)} = A (\text{或} \infty)$, 则
\[
\lim \frac{f(x)}{g(x)} = \lim \frac{f'(x)}{g'(x)} = A (\text{或} \infty)
\]
** 函数单调性的判别
** 函数的极值
*** 函数取得极值的条件                                              :drill:

- 必要条件 :: 设 $f(x)$ 在点 $x_0$ 处取得极值, 且 $f'(x_0)$ 存在, 则 $f'(x_0)=0$.

- 第一充分条件 :: 设 $f(x)$ 在点 $x_0$ 处连续, 在 $\mathring{U}(x_0)$ 内可导.
1. 若在 $x_0$ 的左侧邻域内 $f'(x)>0$, 右侧邻域内 $f'(x)<0$, 则 $f(x_0)$ 为极大值.
2. 若在 $x_0$ 的左侧邻域内 $f'(x)<0$, 右侧邻域内 $f'(x)>0$, 则 $f(x_0)$ 为极小值.
3. 若 $x \in \mathring{U}(x_0)$ 时, $f'(x)$ 的符号保持不变, 则 $f(x)$ 在 $x_0$ 处没有极值.

- 第二充分条件 :: 设 $f(x)$ 在点 $x_0$ 处 $n$ 阶可导, 且 
\[
f'(x_0) = f''(x_0) = \cdots = f^{(n-1)}(x_0) = 0, f^{(n)}(x_0) \neq 0 (n \geqslant 2).
\]
1. 若 $n$ 为偶数, 且 $f^{(n)}(x_0)<0$, 则 $f(x_0)$ 为极大值.
2. 若 $n$ 为偶数, 且 $f^{(n)}(x_0)>0$, 则 $f(x_0)$ 为极小值.
3. 若 $n$ 为奇数, 则 $f(x_0)$ 不是极值.

** 函数图形的凹凸性、拐点及渐近线
*** 拐点的判别方法                                                  :drill:

- 必要条件 :: 设 $(x_0, f(x_0))$ 是曲线 $y=f(x)$ 的拐点, 且 $f''(x)$ 存在, 则 $f''(x_0)=0$.

- 第一充分条件 :: 设 $f(x)$ 在点 $x_0$ 处连续, 在 $\mathring{U}(x_0)$ 内二阶可导.
若在点 $x_0$ 的左右邻域内 $f''(x)$ 反号, 则 $(x_0, f(x_0))$ 是曲线 $y=f(x)$ 的拐点.

- 第二充分条件 :: 设 $f(x)$ 在点 $x_0$ 处 $n$ 阶可导, $n \geq 2$, $n$ 为奇数, 且
\[
f''(x_0) = \cdots = f^{(n-1)}(x_0) = 0, f^{(n)}(x_0) \neq 0
\]
则 $(x_0, f(x_0))$ 是曲线 $y=f(x)$ 的拐点.

*** 曲线的渐近线
- 水平渐近线 :: 若 $\lim_{x \to \pm \infty} f(x) = a$, 则 $y=a$ 是曲线 $y=f(x)$ 的水平渐近线.
- 铅直渐近线 :: 若 $\lim_{x \to x_0^{\pm}} f(x) = \infty$, 则 $x=x_0$ 是曲线 $y=f(x)$ 的铅直渐近线.
- 斜渐近线 :: $y=ax+b$ 是曲线 $y=f(x)$ 的斜渐近线当且仅当 
\[
\lim_{x \to \pm \infty} \frac{f(x)}{x} = a, \lim_{x \to \pm \infty} [f(x) - ax] = b.
\]

** 函数图形的描绘
** 函数的最大值与最小值
设 $f(x)$ 在 $[a,b]$ 上连续, 可用如下步骤求 $f(x)$ 在 $[a,b]$ 上的最值:
1. 求出 $f(x)$ 在 $(a,b)$ 内的驻点和不可导点, 并计算相应的函数值
2. 求出 $f(x)$ 在区间端点的函数值
3. 比较 1. 和 2. 中的函数值, 最大者为最大值, 最小者为最小值.

** 弧微分
\[
\dd{s} = \sqrt{1+y'^2} \dd{x}
\]

** 曲率的概念
\[
K = \lim_{\Delta s \to 0} \abs{\frac{\Delta \alpha}{\Delta s}} = \abs{\dv{\alpha}{s}} 
= \frac{\frac{\Delta s}{a}}{\Delta s} = \frac{1}{a}
\]

由 $\tan \alpha = y'$, 所以 \[ \sec^2 \alpha \dv{\alpha}{x} = y'' \]
\[ \dv{\alpha}{x} = \frac{y''}{1+\tan^2 \alpha} = \frac{y''}{1+y'^2} \]

\[ K = \abs{\dv{\alpha}{s}} = \abs{\frac{\dv{\alpha}{x}}{\dv{s}{x}}} = \frac{\abs{y''}}{(1+y'^2)^{\frac{3}{2}}} \]

设曲线由参数方程 $\begin{cases} x=\varphi(t), \\ y=\psi(t). \end{cases}$ 给出, 
则可利用[[由参数方程所确定的函数的二阶导数][由参数方程所确定的函数的求导法]], 求出 $y'_x$ 和 $y''_x$, 代入上式得
\[
K = \frac{\abs{\psi''(t) \varphi'(t) - \psi'(t) \varphi''(t)}}{[\varphi'^2(t) + \psi'^2(t)]^{\frac{3}{2}}}
\]

** 曲率圆与曲率半径
\[ \rho = \frac{1}{K} \]

** *微分学的应用
*** 零点问题
*** 微分不等式
**** 经典不等式                                                    :drill:
SCHEDULED: <2019-10-25 Fri>
:PROPERTIES:
:ID:       72968982-AF73-46DF-9875-68AEDB59BBD3
:DRILL_LAST_INTERVAL: 3.86
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 3.0
:DRILL_EASE: 2.36
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2019-10-21 Mon 19:36]
:END:
- 绝对值不等式
\[ ||a|-|b|| \leqslant |a \pm b| \leqslant |a|+|b| \]

- 均值不等式
\[
\frac{n}{\sum_{i=1}^{n} \frac{1}{x_{i}}} \leqslant \sqrt[n]{\prod_{i=1}^{n} x_{i}} \leqslant \frac{\sum_{i=1}^{n} x_{i}}{n} \leqslant \sqrt{\frac{\sum_{i=1}^{n} x_{i}^{2}}{n}}
\]

- 三角函数
\begin{align*}
\sin x &< x < \tan x  \quad (0<x<\frac{\pi}{2}) \\
\arctan x &\leqslant x \leqslant \arcsin x \quad (0 \leqslant x \leqslant 1)
\end{align*}

- 幂指函数
\begin{align*}
\ln x + 1 \leqslant x \leqslant e^x -1 \quad (\forall x)
\end{align*}

* 一元函数积分学 
1. 理解原函数的概念, 理解不定积分和定积分的概念
2. 掌握不定积分的基本公式, 掌握不定积分和定积分的性质及定积分中值定理, 掌握换元积分法与分部积分法.
3. 会求有理函数、三角函数有理式和简单无理函数的积分.
4. 理解积分上限的函数, 会求它的导数, 掌握牛顿-莱布尼茨公式.
5. 了解反常积分的概念, 会计算反常积分.
6. 掌握用定积分表达和计算一些几何量与物理量(平面图形的面积、平面曲线的弧长、旋转体的体积及侧面积、平行截面面积为已知的立体体积、功、引力、压力、质心、形心等)及函数平均值.

** 原函数和不定积分的概念
*** 原函数
对于函数 $f(x)$ 和可导函数 $F(x)$, 如果对 $[a,b]$ 上任何一点 $x$, 有 $F'(x) = f(x)$, 则称 $F(x)$ 为 $f(x)$ 在 $[a,b]$ 上的一个原函数.

*** 不定积分
如果 $F(x)$ 是 $f(x)$ 的一个原函数, 则 $F(x) + C$ 是 $f(x)$ 的全体原函数, 并叫做 $f(x)$ 的不定积分, 记作 $\int f(x) \dd{x}$, 即
\[ \int f(x) \dd{x} = F(x) + C \]
其中 $C$ 为任意常数.

** 不定积分的基本性质
** 基本积分公式                                                      :drill:
SCHEDULED: <2019-10-25 Fri>
:PROPERTIES:
:ID:       71C7C97E-0D98-4DD1-AC07-84AE299ED19B
:DRILL_LAST_INTERVAL: 3.86
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 5
:DRILL_FAILURE_COUNT: 2
:DRILL_AVERAGE_QUALITY: 2.4
:DRILL_EASE: 2.08
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2019-10-21 Mon 18:04]
:END:
\begin{align*}
  \int \sec ^{2} x \dd{x} &= \tan x+C & \int \sec x \dd{x} &= \ln \abs{\sec x+\tan x} + C \\
  \int \csc ^{2} x \dd{x} &= -\cot x+C & \int \csc x \dd{x} &= \ln \abs{\csc x-\cot x} + C \\
\\
  \int \frac{1}{\sqrt{a^2-x^2}} \dd{x} &= \arcsin \frac{x}{a} + C
                                      & \int \frac{1}{\sqrt{x^2 \pm a^2}} \dd{x} &= \ln \abs{x+\sqrt{x^2 \pm a^2}} + C \\
  \int \frac{1}{a^2+x^2} \dd{x} &= \frac{1}{a} \arctan \frac{x}{a} + C
                                      & \int \frac{1}{a^2-x^2} \dd{x} &= \frac{1}{2a} \ln \abs{\frac{a+x}{a-x}} + C \\
\\
  \int \sqrt{a^2-x^2} \dd{x} &= \frac{x}{2} \sqrt{a^2-x^2} + \frac{a^2}{2} \arcsin \frac{x}{a} + C
                                      & \int \sqrt{x^2 \pm a^2} \dd{x} &= \frac{x}{2} \sqrt{x^2 \pm a^2} + \frac{a^2}{2} \ln \abs{x+\sqrt{x^2 \pm a^2}} + C \\
\end{align*}

** 定积分的概念和基本性质
*** 定积分(黎曼 Riemann 积分)的定义
设有常数 $I$, 如果对于任意 $\varepsilon > 0$, 总存在 $\delta >0$, 使得对于区间 $[a,b]$ 的任何分法, 不论 $\xi_i$ 在 $[x_{i-1}, x_i]$ 中怎样选取,
只要 $\lambda = \max \qty{\Delta x_i} < \delta$, 总有
\[ \abs{\sum_{i=1}^n f(\xi_i)\Delta x_i - I} < \varepsilon \]
成立, 那么称 $I$ 是 $f(x)$ 在区间 $[a,b]$ 上的定积分, 记作 $\int_a^b f(x) \dd{x}$, 即
\[ \int_a^b f(x) \dd{x} = I = \lim_{\lambda \to 0} \sum_{i=1}^n f(\xi_i)\Delta x_i \]

*** 可积的条件
- 必要条件 :: 若 $f(x)$ 在 $[a,b]$ 上可积, 则 $f(x)$ 在 $[a,b]$ 上一定有界.
- 第一充分条件 :: 设 $f(x)$ 在 $[a,b]$ 上连续, 则 $f(x)$ 在 $[a,b]$ 上可积.
- 第二充分条件 :: 设 $f(x)$ 在 $[a,b]$ 上有界, 且仅有有限个第一类间断点, 则 $f(x)$ 在 $[a,b]$ 上可积.
- 第三充分条件 :: 设 $f(x)$ 在 $[a,b]$ 上单调有界, 则 $f(x)$ 在 $[a,b]$ 上可积.

*** 定积分的性质
**** 定积分的线性性质
**** 定积分的可加性
**** 定积分的保号性
\begin{theorem}
如果在区间 $[a,b]$ 上 $f(x) \geqslant 0$, 那么
\[ \int_a^b f(x) \dd{x} \geqslant 0 \quad (a<b) \]
\end{theorem}

\begin{deduction}
如果在区间 $[a,b]$ 上 $f(x) \leqslant g(x)$, 那么
\[ \int_a^b f(x) \dd{x} \leqslant \int_a^b g(x) \dd{x} \quad (a<b) \]
\end{deduction}

\begin{deduction}
\[
\abs{\int_a^b f(x) \dd{x}} \leqslant \int_a^b \abs{f(x)} \dd{x} \quad (a<b)
\]
\end{deduction}

**** 定积分的估值定理
\begin{theorem}
设 $M$ 及 $m$ 分别是函数 $f(x)$ 在区间 $[a,b]$ 上的最大值及最小值, 则
\[ m(b-a) \leqslant \int_a^b f(x) \dd{x} \leqslant M(b-a) \quad (a<b) \]
\end{theorem}

** 定积分中值定理
\begin{theorem}
如果函数 $f(x)$ 在积分区间 $[a,b]$ 上连续, 那么在 $[a,b]$ 上至少存在一个点 $\xi$, 使得
\[ \int_a^b f(x) \dd{x} = f(\xi)(b-a) \quad (a \leqslant \xi \leqslant b) \]
\end{theorem}

\begin{deduction}
设 $f(x)$ 在 $[a,b]$ 上连续, $g(x)$ 在 $[a,b]$ 上可积且不变号, 则存在 $\xi \in [a,b]$, 使得
\[ \int_a^b f(x)g(x) \dd{x} = f(\xi) \int_a^b g(x) \dd{x} \]
\end{deduction}

** 积分上限的函数及其导数
\begin{theorem}[原函数存在定理]
设函数 $f(x)$ 在区间 $[a,b]$ 上连续, 则积分上限的函数 $F(x) = \int_a^x f(t) \dd{t}$ 在 $[a,b]$ 上可导, 且
\[ F'(x) = \dv{x} \int_a^x f(t) \dd{t} = f(x) \]
即 $F(x)$ 是 $f(x)$ 在 $[a,b]$ 上的一个原函数.
\end{theorem}

\[
\qty[\int_{v(x)}^{u(x)} f(t) \dd{t}]' = f[u(x)]u'(x) - f[v(x)]v'(x)
\]

** 牛顿-莱布尼兹(Newton-Leibniz)公式
\begin{theorem}
若函数 $f(x)$ 在 $[a,b]$ 上可积, $F(x)$ 为 $f(x)$ 的一个原函数, 则
\[ \int_a^b f(x) \dd{x} = \eval{F(x)}_a^b = F(b) - F(a) \]
\end{theorem}

** 不定积分和定积分的换元积分法与分部积分法
*** 第一类换元积分法(凑微分法)
*** 第二类换元积分法
常用的换元公式:
1. $\int R(x;\sqrt{a^2+x^2}) \dd{x}$, 令 $x=a \tan u$ 或 $x=a \cot u$.
2. $\int R(x;\sqrt{a^2-x^2}) \dd{x}$, 令 $x=a \sin u$ 或 $x=a \cos u$.
3. $\int R(x;\sqrt{x^2-a^2}) \dd{x}$, 令 $x=a \sec u$ 或 $x=a \csc u$.
4. $\int R(x;\sqrt[n]{ax+b}) \dd{x}$, 令 $u=\sqrt[n]{ax+b}$.
5. $\int R(x;\sqrt[m]{x}\sqrt[n]{x}) \dd{x}$, 令 $u=\sqrt[k]{x}$, $k=\lcm(m,n)$.
6. $\int R(x;\sqrt{ax^2+bx+c}) \dd{x}$, 配方.

*** 分部积分法
设 $u=u(x)$, $v=v(x)$ 均有连续的导数, 则
\[
\int u \dd{v} = uv -\int v \dd{u}
\]

** 有理函数、三角函数的有理式和简单无理函数的积分
*** 有理函数积分
1. 看分子分母最高项的次数, 如有必要请做除法.
2. 对分母进行因式分解. 使用二次公式或 _猜想一个根, 然后再做除法_ .
3. 分部. (分部仅由分母决定)
   - 线性式 $(x+a)$ :: \[ \frac{A}{x+a} \]
   - 线性式的平方 $(x+a)^2$ :: \[ \frac{A}{(x+a)^2} + \frac{B}{x+a} \] 高阶可递推得之.
   - 二次多项式 $(x^2+ax+b)$ :: \[ \frac{Ax+B}{x^2+ax+b} \]
   
   被积函数 = 分部
4. 计算常数的值. 
   - 换掉 $x$ 的值.
   - 系数相等法.
5. 求解分母为线性项次幂的积分.
   - 对数形式.
   - 线性项的负次幂.
6. 对分母是二次函数的被积函数求积分.
   - [[第一类换元积分法(凑微分法)][凑微分法]]
   - 先配方, 然后换元, 分解为两个积分
     1. 对数函数
     2. 反正切函数

*** 三角函数有理式积分
**** 万能代换
\begin{gather*}
t = \tan \frac{x}{2} \\
\sin x = \frac{2t}{1+t^2} \qc \cos x = \frac{1-t^2}{1+t^2} \qc \dd{x} = \frac{2 \dd{t}}{1+t^2}
\end{gather*}

*** 简单无理数积分
**** 变量代换使有理化
** *关于定积分的几个重要结论
- 利用圆的面积
\[ \int_0^a \sqrt{a^2 - x^2} \dd{x} = \frac{1}{4} \pi a^2 \]

- 利用奇函数/偶函数的对称性
\begin{equation*}
\int_{-a}^a f(x) \dd{x} =
\begin{cases}
0 & f \text{为奇函数}, \\
2 \int_0^a f(x) \dd{x} & f \text{为偶函数}, \\
\int_{-a}^a \frac{f(x)+f(-x)}{2} & f \text{非奇非偶}.
\end{cases}
\end{equation*}

- 利用函数的周期性
\begin{align*}
\int_a^{a+T} f(x) \dd{x} &= \int_0^T f(x) \dd{x} \\
\int_a^{a+nT} f(x) \dd{x} &= n \int_0^T f(x) \dd{x}, n \in \mathbf{N}.
\end{align*}

- 区间再现公式
\[ \int_a^b f(x) \dd{x} = \int_a^b f(a+b-x) \dd{x} \]

\[ \int_0^{\pi} xf(\sin x) \dd{x} = \frac{\pi}{2} \int_0^{\pi} f(\sin x) \dd{x} \]

- 华里士(Wallis)公式
\[
\lim _{n \to +\infty}\left(\frac{(2n)!!}{(2n-1)!!}\right)^2 \frac{1}{2n+1}=\frac{\pi}{2}
\]

- 点火公式
\begin{equation*}
I_n = \int_0^{\frac{\pi}{2}} \sin^n x \dd{x} = \int_0^{\frac{\pi}{2}} \cos^n x \dd{x} = 
\begin{cases}
\frac{n-1}{n} \cdot \frac{n-3}{n-2} \cdot \cdots \cdot \frac{4}{5} \cdot \frac{2}{3} \cdot 1 & n=2k+1, \\
\frac{n-1}{n} \cdot \frac{n-3}{n-2} \cdot \cdots \cdot \frac{3}{4} \cdot \frac{1}{2} \cdot \frac{\pi}{2} & n=2k,
\end{cases}
k \in \mathbf{N}.
\end{equation*}

\[
I_n = \frac{n-1}{n} I_{n-2}
\]

\[
\int_0^{\frac{\pi}{4}} \sin x \dd{x} = 1 - \frac{\sqrt{2}}{2}
\]

\[
\int_0^{\frac{\pi}{2}} f(\sin x, \cos x) \dd{x} = \int_0^{\frac{\pi}{2}} f(\cos x, \sin x) \dd{x}
\]

\begin{align*}
\int_0^{\pi} \sin^n x \dd{x} &= 2 I_n
\\
\int_0^{\pi} \cos^n x \dd{x} &= 
\begin{cases}
0 & n=2k-1, \\
2 I_n & n=2k,
\end{cases}
k \in \mathbf{N}^*.
\\
\int_0^{2\pi} \sin^n x \dd{x} &= \int_0^{2\pi} \cos^n x \dd{x} = 
\begin{cases}
0 & n=2k-1, \\
4 I_n & n=2k,
\end{cases}
k \in \mathbf{N}^*.
\end{align*}

** 反常(广义)积分
*** 常用的反常积分
\begin{align*}
\int_1^{+\infty} \frac{1}{x^p} \dd{x} &=
\begin{cases}
\frac{1}{p-1} & p > 1, \\
+\infty & p \leqslant 1.
\end{cases}
&
\int_a^{+\infty} \frac{\dd{x}}{x(\ln x)^p} &=
\begin{cases}
\frac{1}{p-1}(\ln a)^{1-p} & p > 1, \\
+\infty & p \leqslant 1,
\end{cases}
\qq{其中} a>1.
\\
\int_0^1 \frac{1}{x^q} \dd{x} &=
\begin{cases}
\frac{1}{1-q} & 0<q<1, \\
\infty & q \geqslant 1.
\end{cases}
&
\int_a^b \frac{1}{(x-a)^q} \dd{x} = \int_a^b \frac{1}{(b-x)^q} &=
\begin{cases}
\frac{(b-a)^{1-q}}{1-q} & 0<q<1, \\
\infty & q \geqslant 1.
\end{cases}
\end{align*}
# align 环境不能有空行, 否则会被识别为新的片段

\[ 
\int_0^{+\infty} \frac{\sin x}{x} \dd{x} = \frac{\pi}{2}
\]

*** $\Gamma$ 函数
\[ \Gamma(s) = \int_0^{+\infty} e^{-x} x^{s-1} \dd{x} \quad (s>0)\]
**** 递推公式
\[ \Gamma(s+1) = s\Gamma(s) \quad (s>0) \]
**** 趋向
\[ \Gamma(s) \to +\infty \quad (s \to 0^+) \]
**** 余元公式
\[ \Gamma(s) \Gamma(1-s) = \frac{\pi}{\sin \pi s} \quad (0<s<1) \]
**** 常用公式
\[ \int_0^{+\infty} e^{-x^2} \dd{x} = \frac{\sqrt{\pi}}{2} \]

** 定积分的应用
*** 微元法
*** 平面图形的面积
**** 直角坐标系
**** 极坐标系
\[ S = \frac{1}{2} \int_{\alpha}^{\beta} \varphi^2(\theta) \dd{\theta} \]
\[ S_{\text{扇}} = \frac{1}{2} l r \qc l = \theta r \]

*** 平面曲线的弧长
**** 参数方程
\newline
若曲线 $L$ 的方程为 $\begin{cases} x=x(t), \\ y=y(t),\end{cases} \alpha \leqslant t \leqslant \beta$,
则 $L$ 的弧长为
\[ s = \int_{\alpha}^{\beta} \sqrt{x'^2(t) + y'^2(t)} \dd{t} \]

**** 直角坐标系
\newline
若曲线 $L$ 的方程为 $y=y(x) \qc a \leqslant x \leqslant b$,
则 $L$ 的弧长为
\[ s = \int_a^b \sqrt{1 + y'^2} \dd{x} \]

**** 极坐标系
\newline
若曲线 $L$ 的方程为 $r=r(\theta) \qc \alpha \leqslant \theta \leqslant \beta$,
则 $L$ 的弧长为
\[ s = \int_{\alpha}^{\beta} \sqrt{r^2(\theta) + r'^2(\theta)} \dd{\theta} \]

*** 旋转体的体积及侧面积
- 由曲线 $y=f(x)$ 与直线 $y=0, x=a, x=b (a<b)$ 所围成的平面图形绕 $x$ 轴旋转一周, 生成旋转体的体积和侧面积分别为
\[ V_x = \pi \int_a^b f^2(x) \dd{x}, S_x = 2\pi \int_a^b f(x) \sqrt{1+f'^2(x)} \dd{x} \]

- 设 $f(x)$ 在区间 $[a,b]$ 上连续, 且 $f(x)$ 非负, $a>0$, 则曲线 $y=f(x)$ 与直线 $x=a, x=b$ 及 $x$ 轴所围成的平面图形绕 $y$ 轴旋转所得旋转体体积为
\[ V = 2\pi \int_a^b xf(x) \dd{x} \]

*** 平行截面面积为已知的立体体积
\[ V = \int_a^b S(x) \dd{x} \]

*** 函数的平均值
\[ \bar{y} = \frac{1}{b-a} \int_a^b f(x) \dd{x} \]

* 多元函数微分学
1. 了解多元函数的概念, 了解二元函数的几何意义.
2. 了解二元函数的极限与连续的概念, 了解有界闭区域上二元连续函数的性质.
3. 了解多元函数偏导数和全微分的概念, 会求多元复合函数一阶、二阶偏导数, 会求全微分, 了解隐函数存在定理, 会求多元隐函数的偏导数.
4. 了解多元函数极值和条件极值的概念, 掌握多元函数极值存在的必要条件, 了解二元函数极值存在的充分条件, 会求二元函数的极值, 会用拉格朗日乘数法求条件极值, 会求简单多元函数的最大值和最小值, 并会解决一些简单的应用问题.

** 多元函数的概念
设 $D \subset \mathbf{R}^n \neq \emptyset$, 称映射 $f: D \to \mathbf{R}$ 为定义在 $D$ 上的 $n$ 元函数, 通常记为
\[ u = f(x_1, x_2, \cdots, x_n), (x_1, x_2, \cdots, x_n) \in D \]

** 二元函数的几何意义
二元函数 $z=f(x,y)$ 在几何上一般表示空间直角坐标系中的一个曲面.

** 二元函数的极限与连续的概念
*** 二元函数极限的定义
设函数 $z=f(x,y)$ 在点 $(x_0,y_0)$ 的某去心邻域内有定义, $A$ 为常数. 如果对于任意 $\varepsilon > 0$, 存在 $\delta > 0$,
当 $0<\sqrt{(x-x_0)^2 + (y-y_0)^2}<\delta$ 时, 有 $\abs{f(x,y)-A} < \varepsilon$, 则称函数 $z=f(x,y)$ 当 $(x,y)$ 趋于 $(x_0, y_0)$ 时,
以 $A$ 为极限, 记作 \[ \lim_{(x,y) \to (x_0,y_0)} f(x,y) = A \]

*** 二元函数的连续性
设函数 $z=f(x,y)$ 在点 $P_0(x_0, y_0)$ 的某领域内有定义, 若 $\lim_{(x,y) \to (x_0,y_0)} f(x,y) = f(x_0, y_0)$,
则称函数 $z=f(x,y)$ 在点 $P_0(x_0, y_0)$ 处连续.

** 有界闭区域上二元连续函数的性质
设 $z=f(x,y)$ 在有界闭区域 $D$ 上连续, 则
1. (有界性定理) $f(x,y)$ 在 $D$ 上有界.
2. (最值定理) $f(x,y)$ 在 $D$ 上必取得最大值 $M$ 和最小值 $m$, 即 \[ m \leqslant f(x,y) \leqslant M \]
3. (介值定理) 若 $m \leqslant c \leqslant M$, 存在 $(\xi, \eta) \in D$, 使 $f(\xi, \eta)=c$.

** 多元函数的偏导数和全微分
*** 全微分
如果函数 $z=f(x,y)$ 在点 $(x,y)$ 处的全增量 $\Delta z = f(x+\Delta x, y+\Delta y) - f(x,y)$ 可以表示为
\[ \Delta z = A \Delta x + B \Delta y + o(\rho) \]
其中 $A,B$ 不依赖于 $\Delta x, \Delta y$, 而仅与 $x,y$ 有关, $\rho = \sqrt{(\Delta x)^2 + (\Delta y)^2}$, 则称函数 $z=f(x,y)$ 在点 $(x,y)$
处可微, 称 $A\Delta x+B \Delta y$ 为函数 $z=f(x,y)$ 处的全微分, 记作 $\dd{z}$.

*** 可微的条件
- 必要条件 :: 如果函数 $z=f(x,y)$ 在点 $(x,y)$ 处可微, 则偏导数 $\pdv{z}{x}, \pdv{z}{y}$ 都存在, 且 $\dd{z} = \pdv{z}{x}\dd{x} + \pdv{z}{y}\dd{y}$.
- 充分条件 :: 如果函数 $z=f(x,y)$ 的偏导数 $\pdv{z}{x}, \pdv{z}{y}$ 在点 $(x,y)$ 处连续, 则函数在该点可微.

** 多元复合函数、隐函数的求导法
*** 隐函数求导法则
- 对于由方程 $F(x,y) = 0$ 确定的隐函数 $y=f(x)$, 当 $F'_y(x,y) \neq 0$ 时, 有
\[ \dv{y}{x} = -\frac{F'_x}{F'_y} \]

- 对于由方程 $F(x,y,z)=0$ 确定的隐函数 $z=f(x,y)$, 当 $F'_z(x,y,z) \neq 0$ 时, 有
\[ \pdv{z}{x} = -\frac{F'_x}{F'_z}, \pdv{z}{y} = -\frac{F'_y}{F'_z} \]

- 对于由方程组 $\begin{cases} F(x,y,u,v)=0, \\ G(x,y,u,v)=0, \end{cases}$ 确定的隐函数 $\begin{cases} u=u(x), \\ v=v(x),\end{cases}$ 
当雅可比(Jacobi) 式 \[ J = \pdv{(F,G)}{(u,v)} = \mdet{F'_u & F'_v \\ G'_u & G'_v} \neq 0 \] 时, 有
\[ 
\pdv{u}{x} = -\frac{1}{J} \pdv{(F,G)}{(x,v)} 
= -\frac{\pdv{(F,G)}{(x,v)}}{\pdv{(F,G)}{(u,v)}} 
= -\frac{\mdet{F'_x & F'_v \\ G'_x & G'_v}}{\mdet{F'_u & F'_v \\ G'_u & G'_v}}
\]

$\pdv{u}{y}, \pdv{v}{x}, \pdv{v}{y}$ 可类似得出.

** 二阶偏导数
$\pdv{z}{x}{y}, \pdv{z}{y}{x}$ 为 $z=f(x,y)$ 的两个混合二阶偏导数. 当这两个混合二阶偏导数都连续时, \[ z''_{xy}=z''_{yx} \]

** 多元函数的极值和条件极值、最大值和最小值                          :drill:
SCHEDULED: <2019-10-25 Fri>
:PROPERTIES:
:ID:       9485CD37-2525-48C0-BB66-5ED35D273CA2
:DRILL_LAST_INTERVAL: 3.86
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 5
:DRILL_FAILURE_COUNT: 2
:DRILL_AVERAGE_QUALITY: 2.4
:DRILL_EASE: 2.08
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2019-10-21 Mon 18:04]
:END:
#
*** 二元函数取得极值的必要条件
若 $f(x,y)$ 在点 $(x_0, y_0)$ 处具有偏导数且取得极值, 则 $f'_x=0, f'_y=0$. 这样的点称为驻点.

*** 二元函数取得极值的充分条件
设函数 $z=f(x,y)$ 在点 $(x_0, y_0)$ 的某个领域内具有连续的二阶偏导数, 且 $f'_x=0, f'_y=0$, 令
\[ A=f''_{xx}, B=f''_{xy}, C=f''_{yy} \]
则有:
1. $AC-B^2>0$ 时具有极值, 且当 $A<0$ 时具有极大值, 当 $A>0$ 时具有极小值;
2. $AC-B^2<0$ 时没有极值;
3. $AC-B^2=0$ 时可能有极值, 也可能没有极值, 还需另作讨论.

*** 条件极值与拉格朗日乘数法
为了求函数 $f(x,y)$ 在条件 $\varphi(x,y)=0$ 下的极值, 先构造函数
\[ F(x,y,\lambda) = f(x,y)+\lambda \varphi(x,y) \]
然后解方程组
\begin{equation*}
\begin{cases}
F'_x=0, \\
F'_y=0, \\
F'_{\lambda} = 0,
\end{cases}
\end{equation*}

得到的点 $(x,y,z)$ 就是可能的极值点.
在实际问题中, 可以通过实际问题本身的背景加以确定.

* 多元函数积分学
了解二重积分的概念与基本性质, 掌握二重积分的计算方法(直角座标、极坐标).
** 二重积分的概念、基本性质和计算
*** 二重积分的概念
设函数 $f(x,y)$ 在有界闭区域 $D$ 上有界, $f(x,y)$ 在 $D$ 上的二重积分定义为
\[ \iint \limits_D f(x,y) \dd{\sigma} = \lim_{\lambda \to 0} \sum_{i=1}^n f(\xi_i, \eta_i) \Delta\sigma_i \]

*** 二重积分的性质
- 若 $D=D_1+D_2$, 则
\[ \iint \limits_D f(x,y) \dd{\sigma} = \iint \limits_{D_1} f(x,y) \dd{\sigma} + \iint \limits_{D_2} f(x,y) \dd{\sigma} \]

- (中值定理) 设函数 $f(x,y)$ 在有界闭区域 $D$ 上连续, 则在 $D$ 上至少存在一个点 $(\xi, \eta)$, 使得
\[ \iint \limits_D f(x,y) \dd{\sigma} = f(\xi, \eta) \sigma \]

- 若 $D$ 关于直线 $y=x$ 对称(关于变量 $x$ 和 $y$ 有轮换对称性), 则
\[ \iint \limits_D f(x,y) \dd{\sigma} = \iint \limits_D f(y,x) \dd{\sigma} \]

*** 二重积分的计算
- 利用极坐标计算二重积分:
若 $D:r_1(\theta) \leqslant r \leqslant r_2(\theta), \alpha \leqslant \theta \leqslant \beta$ 则
\[
\iint \limits_D f(x,y) \dd{x}\dd{y} = \iint \limits_D f(r\cos \theta, r\sin \theta)r \dd{r} \dd{\theta}
= \int_{\alpha}^{\beta} \dd{\theta} \int_{r_1(\theta)}^{r_2(\theta)} f(r\cos \theta, r\sin \theta)r \dd{r}
\]

* 常微分方程
1. 了解微分方程及其阶、解、通解、初始条件和特解等概念
2. 掌握变量可分离的微分方程及一阶线性微分方程的解法, 会解齐次方程.
3. 会用降阶法解下列形式的微分方程: $y^{(n)} = f(x), y''=f(x, y')$ 和 $y''=f(y,y')$
4. 理解二阶线性微分方程解的性质及解的结构定理.
5. 掌握二阶常系数齐次线性微分方程的解法, 并会解某些高于二阶的常系数齐次线性微分方程.
6. 会解自由项为多项式、指数函数、正弦函数、余弦函数以及它们的和与积的二阶常系数非齐次线性微分方程.
7. 会用微分方程解决一些简单的应用问题.

** 常微分方程的基本概念
*** 常微分方程的解和初始条件
对于 $n$ 阶常微分方程
\begin{equation}
\label{eq:1}
F(x, y, y', \cdots, y^{(n)}) = 0
\end{equation}
- 解 :: 若函数 $y=\varphi(x)$ 代入方程 \eqref{eq:1} 成为恒等式, 则称 $y=\varphi(x)$ 为方程 \eqref{eq:1} 的解.
- 通解 :: 若方程 \eqref{eq:1} 的解中含有 $n$ 个彼此无关的任意常数, 则称其为方程 \eqref{eq:1} 的通解.
- 初始条件 :: \[ \eval{y}_{x=x_0}=y_0, \eval{y'}_{x=x_0}=y'_0, \cdots, \eval{y^{(n-1)}}_{x=x_0}=y^{(n-1)}_0 \]
- 特解 :: 确定了通解中任意常数的值后的解, 称为方程 \eqref{eq:1} 的特解.

** 变量可分离的微分方程
\[ \dv{y}{x} = f(x)g(y) \]
当 $g(y) \neq 0$ 时, 可写为
\[ \frac{\dd{y}}{g(y)} = f(x) \dd{x} \]
两端积分, 即可得通解
\[ \int \frac{\dd{y}}{g(y)} = \int f(x) \dd{x} \]

** 齐次微分方程
\[ \dv{y}{x} = \varphi(\frac{y}{x}) \]
若令 $u=\frac{y}{x}$, 即 $y=ux$, 有 $\dv{y}{x}=u+x\dv{u}{x}$, 则原方程可变为
\[ u+x\dv{u}{x} = \varphi(u) \]
分离变量, 两端积分
\[ \int \frac{\dd{u}}{\varphi(u)-u} = \int \frac{\dd{x}}{x} \]

** 一阶线性微分方程
\[ \dv{y}{x} + P(x)y = Q(x) \]
的通解为
\[ y=e^{-\int P(x) \dd{x}} \qty[\int Q(x) e^{\int P(x) \dd{x}} \dd{x} + C] \]

** 可降阶的高阶微分方程
- $y^{(n)}=f(x)$ 型方程 :: 只需逐次积分(若每次积分均可进行)即可求得通解.
- $y''=f(x,y')$ 型方程(不含 $y$ 的二阶方程) :: 令 $p=y'$, 则可变为 \[ p'=f(x,p) \]
- $y''=f(y,y')$ 型方程(不含 $x$ 的二阶方程) :: 令 $p=y'$, 则 $y''=\dv{p}{x}=\dv{p}{y} \cdot \dv{y}{x} = p\dv{p}{y}$, 原式可变为 \[ p\dv{p}{y} = f(y,p) \]

** 线性微分方程解的性质及解的结构定理
以二阶线性方程为例
*** 解的性质
1. 齐次线性方程的两个特解, 其 _线性组合_ 仍为该齐次线性方程的解.
2. 非齐次线性方程的两个特解, 其 _差_ 为相应齐次方程的特解.
3. 非齐次线性方程的一个特解 与 相应齐次方程的任意解之 _和_ 仍为该非齐次线性方程的解.
4. (叠加原理)设 $y_1(x)$ 与 $y_2(x)$ 分别是方程 $y''+p(x)y'+q(x)y=f_1(x)$ 与 $y''+p(x)y'+q(x)y=f_2(x)$ 的特解, 则 $y_1(x) + y_2(x)$ 为方程 \[ y''+p(x)y'+q(x)y=f_1(x)+f_2(x) \] 的特解.

*** 解的结构
1. 一阶线性方程的通解
   - 齐次 :: \[ y(x) = Cy_1(x) \]
   - 非齐次 :: \[ y(x) = Cy_1(x) + y^*(x) \]
2. 二阶线性方程的通解
   - 齐次 :: \[ y(x) = C_1 y_1(x) + C_2 y_2(x) \]
   - 非齐次 :: \[ y(x) = C_1 y_1(x) + C_2 y_2(x) + y^*(x) \]

** 二阶常系数齐次线性微分方程
\[ y''+py'+qy = 0 \]
其中 $p,q$ 为常数, 对应的特征方程为
\[ r^2+pr+q = 0 \]
\[ \Delta = p^2-4q \qc r_{1,2} = \frac{-p \pm \sqrt{\Delta}}{2} \]
1. $\Delta > 0$, 即 $r_1 \neq r_2$, 则其通解为 \[ y = C_1 e^{r_1 x} + C_2 e^{r_2 x} \]
2. $\Delta = 0$, 即 $r_1 = r_2 = r$, 则其通解为 \[ y = (C_1+C_2x)e^{rx} \]
3. $\Delta < 0$, 即 $r_{1,2} = \alpha \pm \beta i$, 则其通解为 \[ y = e^{\alpha x}(C_1 \cos \beta x + C_2 \sin \beta x) \]

** 高于二阶的某些常系数齐次线性微分方程
\[
y^{(n)}+p_{1} y^{(n-1)}+p_{2} y^{(n-2)}+\cdots+p_{n-1} y'+p_{n} y=0
\]
其中 $p_i(i=1,2,\cdots,n)$ 为常数, 对应的特征方程为
\[
r^{n}+p_{1} r^{n-1}+p_{2} r^{n-2}+\cdots+p_{n-1} r+p_{n}=0
\]
1. $n$ 个相异实根 $r_1, r_2, \cdots, r_n$, 则其通解为 \[y = C_1 e^{r_1 x} + C_2 e^{r_2 x} + \cdots + C_n e^{r_n x} \]
2. $k(k \leqslant n)$ 重实根 $r$, 则其通解中含有 \[ (C_1+C_2 x+ \cdots + C_k x^{k-1}) e^{rx} \]
3. $k(k \leqslant \frac{n}{2})$ 重共轭复根 $\alpha \pm \beta i$, 则其通解中含有 \[ e^{\alpha x}\qty[\qty(C_{1}+C_{2} x+\cdots+C_{k} x^{k-1}) \cos \beta x+\qty(D_1+D_2 x+\cdots+D_k x^{k-1}) \sin \beta x] \]

** 简单的二阶常系数非齐次线性微分方程
为求方程
\[ y''+py'+qy=f(x) \]
的通解, 只需求出它的一个特解 $y^{*}$, 并与其对应的齐次微分方程的通解作和即得.

1. $f(x)=e^{\lambda x}P_m(x)$
   \[ y^{*} = x^k e^{\lambda x} Q_m(x) \]
   其中 $k$ 按 $\lambda$ _不是特征方程的根_ / _是特征方程的单根_ / _是特征方程的复根_ 分别取 $0/1/2$.

2. $f(x)=e^{\lambda x} \qty[P_l(x) \cos \omega x + Q_n(x) \sin \omega x]$
   \[ y^{*} = x^k e^{\lambda x} \qty[R_m^{(1)}(x) \cos \omega x + R_m^{(2)}(x) \sin \omega x] \]
   其中 $t= \max \qty{l,n}$, 而 $k$ 按 $\lambda \pm \omega i$ _不是特征方程的根_ / _是特征方程的单根_ 分别取 $0/1$.

** 微分方程的简单应用
