#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{ctex, mathtools, amsthm, booktabs, physics, geometry}
#+LATEX_HEADER: \geometry{left=2.5cm, right=2.5cm, top=2cm, bottom=2cm}
#+LATEX_HEADER: \renewcommand\arraystretch{1.5}
#+LATEX_HEADER: \theoremstyle{definition} \newtheorem{definition}{定义}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{theorem}{定理}[section]
#+LATEX_HEADER: \theoremstyle{plain} \newtheorem{deduction}{推论}[section]
#+LATEX_HEADER: \theoremstyle{remark} \newtheorem{remark}{注释}[section]
#+STARTUP: align

* 函数、极限、连续
1. 理解函数的概念, 掌握函数的表示法, 会建立应用问题的函数关系.
2. 了解函数的有界性、单调性、周期性和奇偶性.
3. 理解复合函数及分段函数的概念, 了解反函数及隐函数的概念.
4. 掌握基本初等函数的性质及其图形, 了解初等函数的概念.
5. 理解极限的概念, 理解函数左极限与右极限的概念以及函数极限存在与左极限、右极限之间的关系.
6. 理解无穷小量、无穷大量的概念, 掌握无穷小量的比较方法, 会用等价无穷小量求极限.
7. 掌握极限的性质及四则运算法则.
8. 掌握极限存在的两个法则, 并会利用它们求极限, 掌握利用两个重要极限求极限的方法.
9. 理解函数连续性的概念(含左连续与右连续), 会判别函数间断点的类型.
10. 了解连续函数的性质和初等函数的连续性, 理解闭区间上连续函数的性质(有界性、最大值和最小值定理、介值定理), 并会应用这些性质.

** 函数的概念及表示法
*** 函数的概念
设 $x$ 与 $y$ 是两个变量, 变量 $x$ 的取值范围是非空数集 $D$, 如果对 $D$ 中任意一个 $x$, 
变量 $y$ 按照一定的法则总有 *唯一* 的数值与之对应, 则称变量 $y$ 是变量 $x$ 的函数. 记为
\[
y=f(x) \qq{或} y=y(x)
\]
其中 $x$ 称为自变量, $y$ 称为因变量, $D$ 称为函数 $y=f(x)$ 的定义域.

*** 函数的表示法
- 列表法
- 图像法
- 解析法

** 函数的有界性、单调性、周期性和奇偶性
*** 有界性
设函数 $f(x)$ 的定义域为 $D$, $I \subset D$, 如果存在正数 $M$, 使得对任意 $x \in I$, 
都有 $\abs{f(x)} \leqslant M$, 则称函数 $f(x)$ 在 $I$ 上有界. 如果这样的 $M$ 不存在, 
则称函数 $f(x)$ 在 $I$ 上无界.
 
** 复合函数、反函数、分段函数和隐函数
*** 分段函数
**** 狄利克雷(Dirichlet)函数
\[
D(x)=\lim _{k \to \infty}\left(\lim _{j \to \infty}(\cos (k ! \pi x))^{2 j}\right)
\]

** 基本初等函数的性质及其图形
*** 基本初等函数
**** 常值函数
**** 幂函数
**** 指数函数
**** 对数函数
**** 三角函数
\begin{align*}
\sin(A+B) &= \sin(A) \cos(B) + \cos(A) \sin(B) \\
\cos(A+B) &= \cos(A) \cos(B) - \sin(A) \sin(B)
\end{align*}

***** 倍角公式
\begin{align*}
\sin 2x &= 2 \sin x \cos x \\
\cos 2x &= \cos^2 x - \sin^2 x = 2 \cos^2 x - 1 = 1 - 2\sin^2 x
\end{align*}

***** 降幂公式
\begin{align*}
\sin^2 x &= \frac{1}{2} (1 - \cos 2x) \\
\cos^2 x &= \frac{1}{2} (1 + \cos 2x)
\end{align*}

***** 半角公式
\[
\tan \frac{x}{2} = \frac{1-\cos x}{\sin x} = \frac{\sin x}{1+\cos x}
\]

:hint:
分式上下同乘 $\sin \frac{x}{2}$ 或 $\cos \frac{x}{2}$.
:END:

**** 反三角函数

** 初等函数
由基本初等函数经过有限次四则运算或有限次复合运算而得到的, 并且可以用一个数学式子表示的函数, 称为初等函数.
*** 双曲函数
\begin{align*}
\sinh x &= \frac{e^x-e^{-x}}{2} \\
\cosh x &= \frac{e^x+e^{-x}}{2}
\end{align*}

\begin{align*}
\sinh(x+y) &= \sinh x \cosh y + \cosh x \sinh y \\
\cosh(x+y) &= \cosh x \cosh y + \sinh x \sinh y
\end{align*}

*** 反双曲函数
\begin{align*}
\asin x &= \ln(x+\sqrt{x^2+1}) \qc x \in (- \infty, + \infty) \\
\acos x &= \ln(x+\sqrt{x^2-1}) \qc x \in [1, + \infty) \\
\atan x &= \frac{1}{2} \ln \frac{1+x}{1-x} \qc x \in (-1,1)
\end{align*}

** 函数关系的建立
** 数列极限与函数极限的定义及其性质
*** 数列极限的定义
\begin{definition}
给定数列 ${x_n}$, $a$ 为常数, 如果对于任意 $\varepsilon > 0$, 存在正整数 $N$, 当 $n>N$ 时, 有
\[
\abs{x_n-a} <\varepsilon
\]
则称数列 ${x_n}$ 以 $a$ 为极限, 或称数列 ${x_n}$ 收敛于 $a$, 记为
\[
\lim_{n \to \infty} x_n = a \qq{或} x_n \to a (n \to \infty)
\]
\end{definition}

*** 收敛数列的性质
**** 唯一性
**** 有界性
**** 保号性
**** 一致性
\begin{theorem}[收敛数列与其子数列的关系]
如果数列 ${x_n}$ 收敛于 $a$, 那么它的任一子数列也收敛, 且极限也是 $a$.
\end{theorem}

*** 函数极限的定义
\begin{definition}
设函数 $f(x)$ 在点 $x_0$ 的某去心邻域内有定义, A 为一个常数, 如果对于任意 $\varepsilon > 0$, 存在 $\delta > 0$,
使得当 $0<\abs{x-x_0}<\delta$ 时, 有 
\[ \abs{f(x)-A}<\varepsilon \],
则称函数 $f(x)$ 当 $x \to x_0$ 时以 $A$ 为极限, 记为
\[ \lim_{x \to x_0} f(x) = A \qq{或} f(x) \to A \quad (x \to x_0) \]
\end{definition}

#+CAPTION: 函数极限的定义
#+ATTR_LATEX: :float nil :booktabs t :center t
|                 | $f(x) \to A$                                                                 |
|-----------------+------------------------------------------------------------------------------|
| $x \to x_0$     | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<\abs{x-x_0}<\delta$ 时 |
| $x \to x_{0^+}$ | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0<x-x_0<\delta$ 时       |
| $x \to x_{0^-}$ | $\forall \varepsilon >0$, $\exists \delta>0$, 使当 $0>x-x_0>-\delta$ 时      |
| $x \to \infty$  | $\forall \varepsilon >0$, $\exists X>0$, 使当 $\abs{x}>X$ 时                 |
| $x \to +\infty$ | $\forall \varepsilon >0$, $\exists X>0$, 使当 $x>X$ 时                       |
| $x \to -\infty$ | $\forall \varepsilon >0$, $\exists X>0$, 使当 $x<-X$ 时                      |
|-----------------+------------------------------------------------------------------------------|
|                 | 有 $\abs{f(x)-A}<\varepsilon$                                                |

*** 函数极限的性质
**** 唯一性

**** 局部有界性
\begin{theorem}
若 $\lim f(x) = A$, 则存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x)$ 有界.
\end{theorem}
(对于 $x \to x_0$, $\mathring{U}$ 表示 $0<\abs{x-x_0}<\delta$; 对于 $x \to \infty$, $\mathring{U}$ 表示 $\abs{x}>X$)

**** 局部保号性
\begin{theorem}
若 $\lim f(x) = A>B$, 则存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x)>B$.
\end{theorem}

\begin{deduction}
若存在 $\mathring{U}$, 在 $\mathring{U}$ 内 $f(x) \geqslant B$, 且 $\lim f(x) = A$, 则 $A \geqslant B$.
\end{deduction}

**** 一致性
\begin{theorem}[函数极限与数列极限的关系]
如果极限 $\lim_{x \to x_0}f(x)$ 存在, ${x_n}$ 为函数 $f(x)$ 的定义域内任一收敛于 $x_0$ 的数列,
且满足: $x_n \neq x_0 (n \in N_+)$, 那么相应的函数值数列 ${f(x_n)}$ 必收敛, 且 $\lim_{n \to +\infty} f(x_n) = \lim_{x \to x_0} f(x)$.
\end{theorem}

** 函数的左极限和右极限
[[函数极限的定义]]

** 无穷小量和无穷大量大概念及其关系
*** 无穷小量与极限的关系
\[
\lim_{x \to x_0} f(x) = A \Leftrightarrow A + \alpha(x)
\]
其中 $\lim_{x \to x_0} \alpha(x) = 0$.

** 无穷小量的性质及无穷小量的比较
*** 无穷小量的比较
若 $\lim \dfrac{\beta}{\alpha^k}=c \neq 0 \quad (k>0)$, 称 $\beta$ 是 $\alpha$ 的 $k$ 阶无穷小量.

** 极限的四则运算
设 $\lim f(x)$ 存在, $\lim g(x)$ 不存在, 则 $\lim[f(x) \pm g(x)]$ 不存在.

** 极限存在的两个准则：单调有界准则和夹逼准则
*** 单调有界准则
若数列 ${x_n}$ 单调增加(或单调减少)且有上界 $M$ (或有下界 $m$ ), 则 $x_n$ 收敛,
且 $\lim_{n \to \infty} x_n \leqslant M$(或 $\lim_{n \to \infty} x_n \geqslant m$).

*** 夹逼准则
设三个数列满足 $y_n \leqslant x_n \leqslant z_n$, 且 $\lim_{n \to \infty} y_n = \lim_{n \to \infty} z_n = a$, 则 $\lim_{n \to \infty} x_n = a$.

夹逼准则对于函数极限也成立.

** 两个重要极限
\[
\lim_{x \to 0} \frac{\sin x}{x} = 1
\]
\[
\lim_{x \to 0} (1+x)^{\frac{1}{x}} = \lim_{x \to \infty}\left( 1+\frac{1}{x} \right)^x = e
\]

** 函数连续的概念
设函数 $y=f(x)$ 在点 $x_0$ 的某一领域内有定义, 极限 $\lim_{x \to x_0}f(x)$ 存在, 且 $\lim_{x \to x_0}f(x) = f(x_0)$,
则称函数 $y=f(x)$ 在点 $x_0$ 处连续, 并称 $x_0$ 是 $f(x)$ 的连续点.

** 函数间断点的类型
- 可去间断点
- 跳跃间断点
- 无穷间断点
- 振荡间断点

** 初等函数的连续性
一切初等函数在其定义区间内都连续.

** 闭区间上连续函数的性质
设 $f(x)$ 在 $[a,b]$ 上连续, 则
1. (有界性定理) $f(x)$ 在 $[a,b]$ 上有界.
2. (最值定理) 存在 $\xi_1, \xi_2 \in [a,b]$, 使 \[ f(\xi_1) = M = \max_{x \in [a,b]}f(x), \quad f(\xi_2) = m = \min_{x \in [a,b]} f(x) \]
3. (介值定理) 对于任意 $\mu: m \leqslant \mu \leqslant M$, 存在 $\xi \in [a,b]$, 使 $f(\xi)=\mu$.
特别地, 若 $f(a)f(b)<0$, 则存在 $\xi \in (a,b)$, 使 $f(\xi)=0$.

* 一元函数微分学
** 导数和微分的概念
*** 导数的定义
\begin{definition}
设函数 $f(x)$ 在 $U(x_0)$ 内有定义, 若极限
\[ \lim_{\Delta x \to 0} \frac{\Delta y}{\Delta x} = \lim_{\Delta x \to 0} \frac{f(x_0+\Delta x) - f(x_0)}{\Delta x} \]
存在, 则称函数 $f(x)$ 在点 $x=x_0$ 处可导,并称这个极限为 $f(x)$ 在点 $x_0$ 处的导数,
记为 $f'(x_0)$ 或 $\eval{\dv{y}{x}}_{x=x_0}$ 等.
\end{definition}

导数定义的等价形式:
\[
f'(x_0) = \lim_{h \to 0} \frac{f(x_0)+h - f(x_0)}{h} = \lim_{x \to x_0} \frac{f(x) - f(x_0)}{x - x_0}
\]

*** 微分的定义
\begin{definition}
设函数 $f(x)$ 在 $U(x_0)$ 内有定义, $x_0+\Delta x \in U(x_0)$, 如果
\[ \Delta y = f(x_0+\Delta x) - f(x_0) = A \Delta x + o(\Delta x), \]
则称函数 $f(x)$ 在点 $x=x_0$ 处可微,
称 $\dd{y} = A \Delta x$ 为 $f(x)$ 在点 $x=x_0$ 处的微分.
\end{definition}

** 导数的几何意义和物理意义

** 函数的可导性与连续性之间的关系
可导 $\Rightarrow$ 连续

** 平面曲线的切线和法线

** 导数和微分的四则运算

** 基本初等函数的导数
\begin{align*}
  (\arcsin x)' &= \frac{1}{\sqrt{1-x^2}} & (\arctan x)' &= \frac{1}{1+x^2}  \\
  (\arccos x)' &= -\frac{1}{\sqrt{1-x^2}} & (\arccot x)' &= -\frac{1}{1+x^2}
\end{align*}

** 复合函数、反函数、隐函数以及参数方程所确定的函数的微分法

*** 复合函数的导数
\begin{align*}
{f[g(x)]}' &= \dv{\{f[g(x)]\}}{x} \\
f'[g(x)] &= \dv{\{f[g(x)]\}}{[g(x)]}
\end{align*}

** 高阶导数
*** 运算法则

**** 莱布尼茨(Leibniz)公式
\[
(uv)^{(n)} = \sum_{k=0}^n \mathrm{C}_n^k u^{(n-k)} v^{(k)}
\]

:remarks:
可以参考二项式定理(binomial theorem):
\[
(x+y)^n = \sum_{k=0}^n \mathrm{C}_n^k x^{n-k} y^k
\]
其中 $\mathrm{C}_n^k = \frac{n!}{k!(n-k)!}$
:END:

*** 常用的 $n$ 阶导数公式
\begin{align*}
(\sin x)^{(n)} &= \sin(x+\frac{n \pi}{2}) & \left( \frac{1}{ax+b} \right)^{(n)} &= (-1)^n \frac{a^n n!}{(ax+b)^{n+1}} \\
(\cos x)^{(n)} &= \cos(x+\frac{n \pi}{2}) & [\ln(ax+b)]^{(n)} &= (-1)^{n-1} \frac{a^n (n-1)!}{(ax+b)^n}
\end{align*}

*** 由参数方程所确定的函数的二阶导数
设 $\begin{cases} x=x(t), \\ y=y(t). \end{cases}$ $x(t)$ 和 $y(t)$ 可导, 且 $x'(t) \neq 0$, 则
\[
\dv[2]{y}{x} = \dv{t}(\frac{y'_t}{x'_t}) \dv{t}{x} = \frac{y''_{tt} x'_t - y'_t x''_{tt}}{(x'_t)^3}
\]

*** 反函数的二阶导数
设 $y=f(x)$ 二阶可导, 记 $f'(x) = y'_x$, 记其反函数 $x=\varphi(y)$ 的导数 $\varphi'(y) = x'_y \neq 0$, 则有
\[
y''_{xx} = \dv[2]{y}{x} = \dv{\dv{y}{x}}{x} = \dv{\frac{1}{x'_y}}{y} \dv{y}{x} = - \frac{x''_{yy}}{(x'_y)^2} \frac{1}{x'_y} = 
-\frac{x''_{yy}}{(x'_y)^3}
\]

** 一阶微分形式的不变性
对 $y=f(u)$, 不论 $u$ 是自变量还是中间变量, 均有 $\dd{y} = f'(u) \dd{u}$.

** 微分中值定理
*** 费马(Fermat)定理
\begin{theorem}[费马引理]
设函数 $f(x)$ 在点 $x_0$ 的某领域 $U(x_0)$ 内有定义, 并且在 $x_0$ 处可导, 如果对任意的 $x \in U(x_0)$, 有
$f(x) \leqslant f(x_0)$ (或 $f(x) \geqslant f(x_0)$), 则 $f'(x_0) = 0$.
\end{theorem}

*** 罗尔(Rolle)定理
\begin{theorem}
设 $f(x)$ 在 $[a,b]$ 上连续, 在 $(a,b)$ 内可导, 且 $f(a)=f(b)$, 则存在 $\xi \in (a,b)$, 使
\[ f'(\xi) = 0 \]
\end{theorem}

*** 拉格朗日(Lagrange)中值定理
\begin{theorem}
设 $f(x)$ 在 $[a,b]$ 上连续, 在 $(a,b)$ 内可导, 则存在 $\xi \in (a,b)$, 使
\[ f(b)-f(a) = f'(\xi)(b-a) \]
\end{theorem}

*** 柯西(Cauchy)中值定理
\begin{theorem}
设 $f(x), g(x)$ 在 $[a,b]$ 上连续, 在 $(a,b)$ 内可导, 且 $g'(x) \neq 0$, 则存在 $\xi \in (a,b)$, 使
\[ \frac{f(b)-f(a)}{g(b)-g(a)} = \frac{f'(\xi)}{g'(\xi)} \]
\end{theorem}

*** 泰勒(Taylor)公式
\[
f(x)=\sum_{n=0}^N \frac{f^{(n)}(a)}{n!}(x-a)^n + R_n(x)
\]

- 拉格朗日余项 :: $R_n(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-a)^{n+1}$, $\xi$ 介于 $x$ 和 $a$ 之间.

- 佩亚诺(Peano)余项 :: $R_n(x)=o(x^n)$

#+CAPTION: 几个常用的麦克劳林(Maclaurin)展开式 (省略余项)
#+ATTR_LATEX: :float nil :booktabs t :center t
|    $f(x)$    | $f(0)$ | $f'(0)x$ | $\frac{f''(0)}{2!}x^2$ |   $\frac{f'''(0)}{3!}x^3$   |                    $n^{\mathrm{th}}$                     |
|--------------+--------+----------+------------------------+-----------------------------+----------------------------------------------------------|
|      /       |   <    |          |                        |              >              |                            <                             |
|     <c>      |  <c>   |   <c>    |          <c>           |             <c>             |                           <c>                            |
|    $e^x$     |  $1$   |   $x$    |   $\frac{1}{2!}x^2$    |      $\frac{1}{3!}x^3$      |                    $\frac{1}{n!}x^n$                     |
|  $\cos{x}$   |  $1$   |          |   $-\frac{1}{2!}x^2$   |                             |              $(-1)^n\frac{1}{(2n)!}x^{2n}$               |
|  $\sin{x}$   |        |   $x$    |                        |     $-\frac{1}{3!}x^3$      |          $(-1)^{n-1}\frac{1}{(2n-1)!}x^{2n-1}$           |
| $\arcsin{x}$ |        |   $x$    |                        |      $\frac{1}{3!}x^3$      |               $\frac{1}{(2n-1)!}x^{2n-1}$                |
|  $\tan{x}$   |        |   $x$    |                        |      $\frac{1}{3}x^3$       | $(-1)^{n-1}\frac{2^{2n}(2^{2n}-1)B_{2n}}{(2n)!}x^{2n-1}$ |
| $\arctan{x}$ |        |   $x$    |                        |      $-\frac{1}{3}x^3$      |              $(-1)^n\frac{1}{2n-1}x^{2n-1}$              |
|  $\ln(1+x)$  |        |   $x$    |   $-\frac{1}{2}x^2$    |      $\frac{1}{3}x^3$       |                $(-1)^{n-1}\frac{1}{n}x^n$                |
|  $(1+x)^m$   |  $1$   |   $mx$   | $\frac{m(m-1)}{2!}x^2$ | $\frac{m(m-1)(m-2)}{3!}x^3$ |            $\frac{m(m-1)\dots(m-n+1)}{n!}x^n$            |

[[http://mathworld.wolfram.com/MaclaurinSeries.html][其他公式查询]]

** 洛必达(L' Hospital)法则
设在自变量的同一变化过程中, $\lim f(x) = 0 (\text{或} \infty)$, $\lim g(x) = 0 (\text{或} \infty)$,
且 $f(x), g(x)$ 可导, $g'(x) \neq 0$, $\lim \frac{f'(x)}{g'(x)} = A (\text{或} \infty)$, 则
\[
\lim \frac{f(x)}{g(x)} = \lim \frac{f'(x)}{g'(x)} = A (\text{或} \infty)
\]
** 函数单调性的判别

** 函数的极值

*** 函数取得极值的条件

- 必要条件 :: 设 $f(x)$ 在点 $x_0$ 处取得极值, 且 $f'(x_0)$ 存在, 则 $f'(x_0)=0$.

- 第一充分条件 :: 设 $f(x)$ 在点 $x_0$ 处连续, 在 $\mathring{U}(x_0)$ 内可导.
1. 若在 $x_0$ 的左侧邻域内 $f'(x)>0$, 右侧邻域内 $f'(x)<0$, 则 $f(x_0)$ 为极大值.
2. 若在 $x_0$ 的左侧邻域内 $f'(x)<0$, 右侧邻域内 $f'(x)>0$, 则 $f(x_0)$ 为极小值.
3. 若 $x \in \mathring{U}(x_0)$ 时, $f'(x)$ 的符号保持不变, 则 $f(x)$ 在 $x_0$ 处没有极值.

- 第二充分条件 :: 设 $f(x)$ 在点 $x_0$ 处 $n$ 阶可导, 且 
\[
f'(x_0) = f''(x_0) = \cdots = f^{(n-1)}(x_0) = 0, f^{(n)}(x_0) \neq 0 (n \geqslant 2).
\]
1. 若 $n$ 为偶数, 且 $f^{(n)}(x_0)<0$, 则 $f(x_0)$ 为极大值.
2. 若 $n$ 为偶数, 且 $f^{(n)}(x_0)>0$, 则 $f(x_0)$ 为极小值.
3. 若 $n$ 为奇数, 则 $f(x_0)$ 不是极值.

** 函数图形的凹凸性、拐点及渐近线

*** 拐点的判别方法

- 必要条件 :: 设 $(x_0, f(x_0))$ 是曲线 $y=f(x)$ 的拐点, 且 $f''(x)$ 存在, 则 $f''(x_0)=0$.

- 第一充分条件 :: 设 $f(x)$ 在点 $x_0$ 处连续, 在 $\mathring{U}(x_0)$ 内二阶可导.
若在点 $x_0$ 的左右邻域内 $f''(x)$ 反号, 则 $(x_0, f(x_0))$ 是曲线 $y=f(x)$ 的拐点.

- 第二充分条件 :: 设 $f(x)$ 在点 $x_0$ 处 $n$ 阶可导, $n \geq 2$, $n$ 为奇数, 且
\[
f''(x_0) = \cdots = f^{(n-1)}(x_0) = 0, f^{(n)}(x_0) = 0
\]
则 $(x_0, f(x_0))$ 是曲线 $y=f(x)$ 的拐点.

*** 曲线的渐近线
- 水平渐近线 :: 若 $\lim_{x \to \pm \infty} f(x) = a$, 则 $y=a$ 是曲线 $y=f(x)$ 的水平渐近线.
- 铅直渐近线 :: 若 $\lim_{x \to x_0^{\pm}} f(x) = \infty$, 则 $x=x_0$ 是曲线 $y=f(x)$ 的铅直渐近线.
- 斜渐近线 :: $y=ax+b$ 是曲线 $y=f(x)$ 的斜渐近线当且仅当 
\[
\lim_{x \to \pm \infty} \frac{f(x)}{x} = a, \lim_{x \to \pm \infty} [f(x) - ax] = b.
\]

** 函数图形的描绘

** 函数的最大值与最小值
设 $f(x)$ 在 $[a,b]$ 上连续, 可用如下步骤求 $f(x)$ 在 $[a,b]$ 上的最值:
1. 求出 $f(x)$ 在 $(a,b)$ 内的驻点和不可导点, 并计算相应的函数值
2. 求出 $f(x)$ 在区间端点的函数值
3. 比较 1. 和 2. 中的函数值, 最大者为最大值, 最小者为最小值.

** 弧微分
\[
\dd{s} = \sqrt{1+y'^2} \dd{x}
\]

** 曲率的概念
\[
K = \lim_{\Delta s \to 0} \abs{\frac{\Delta \alpha}{\Delta s}} = \abs{\dv{\alpha}{s}} 
= \frac{\frac{\Delta s}{a}}{\Delta s} = \frac{1}{a}
\]

由 $\tan \alpha = y'$, 所以 \[ \sec^2 \alpha \dv{\alpha}{x} = y'' \]
\[ \dv{\alpha}{x} = \frac{y''}{1+\tan^2 \alpha} = \frac{y''}{1+y'^2} \]

\[ K = \abs{\dv{\alpha}{s}} = \abs{\frac{\dv{\alpha}{x}}{\dv{s}{x}}} = \frac{\abs{y''}}{(1+y'^2)^{\frac{3}{2}}} \]

设曲线由参数方程 $\begin{cases} x=\varphi(t), \\ y=\psi(t). \end{cases}$ 给出, 
则可利用[[由参数方程所确定的函数的二阶导数][由参数方程所确定的函数的求导法]], 求出 $y'_x$ 和 $y''_x$, 代入上式得
\[
K = \frac{\abs{\psi''(t) \varphi'(t) - \psi'(t) \varphi''(t)}}{[\varphi'^2(t) + \psi'^2(t)]^{\frac{3}{2}}}
\]

** 曲率圆与曲率半径
\[ \rho = \frac{1}{K} \]

* 一元函数积分学
** 原函数和不定积分的概念
** 不定积分的基本性质
** 基本积分公式
\begin{align*}
  \int \sec ^{2} x \dd{x} &= \tan x+C & \int \sec x \dd{x} &= \ln \abs{\sec x+\tan x} + C \\
  \int \csc ^{2} x \dd{x} &= -\cot x+C & \int \csc x \dd{x} &= \ln \abs{\csc x-\cot x} + C \\
  \\
  \int \frac{1}{\sqrt{a^2-x^2}} \dd{x} &= \arcsin \frac{x}{a} + C 
                                      & \int \frac{1}{a^2+x^2} \dd{x} &= \frac{1}{a} \arctan \frac{x}{a} + C \\
  \int \frac{1}{\sqrt{x^2 \pm a^2}} \dd{x} &= \ln \abs{x+\sqrt{x^2 \pm a^2}} + C
                                      & \int \frac{1}{a^2-x^2} \dd{x} &= \frac{1}{2a} \ln \abs{\frac{a+x}{a-x}} + C \\
\end{align*}

** 定积分的概念和基本性质

** 定积分中值定理

** 积分上限的函数及其导数

** 牛顿-莱布尼兹(Newton-Leibniz)公式

** 不定积分和定积分的换元积分法与分部积分法
*** 分部积分法
设 $u=u(x)$, $v=v(x)$ 均有连续的导数, 则
\[
\int u \dd{v} = uv -\int v \dd{u}
\]

** 有理函数、三角函数的有理式和简单无理函数的积分

** 反常(广义)积分

** 定积分的应用

* 多元函数微积分学
** 多元函数的概念

** 二元函数的几何意义

** 二元函数的极限与连续的概念

** 有界闭区域上二元连续函数的性质

** 多元函数的偏导数和全微分

** 多元复合函数、隐函数的求导法

** 二阶偏导数

** 多元函数的极值和条件极值、最大值和最小值

** 二重积分的概念、基本性质和计算

* 常微分方程
** 常微分方程的基本概念

** 变量可分离的微分方程

** 齐次微分方程

** 一阶线性微分方程

** 可降阶的高阶微分方程

** 线性微分方程解的性质及解的结构定理

** 二阶常系数齐次线性微分方程

** 简单的二阶常系数非齐次线性微分方程

** 微分方程的简单应用
